import type { UiLocale } from "@/lib/locale";
import { plural, type PluralForms } from "@/lib/plural";

/**
 * Arabic chrome (DR-005). Keys, not sentences in JSX. Unknown key → the key
 * (missing copy stays visible). Interpolated money/counts are helpers below.
 * Optional English is a second table for the EN/ع toggle — not next-intl.
 */
const ARABIC: Record<string, string> = {
  "doc.title": "ملاعب",
  "public.day": "اليوم",
  "public.today": "اليوم",
  "public.tomorrow": "غداً",
  "public.otherDate": "تاريخ آخر",
  "public.showHours": "عرض الساعات",
  "public.hours": "الساعات",
  "public.taken": "محجوز",
  "public.until": "حتى",
  "public.name": "الاسم",
  "public.phone": "الهاتف",
  "public.request": "اطلب",
  "public.emptyPitches": "لا ملاعب بعد.",
  "public.emptyPitchesNext": "هذا الملعب لم يُدرج ملاعب.",
  "public.closed": "مغلق هذا اليوم.",
  "public.closedNext": "اختر يوماً آخر لرؤية الساعات.",
  "public.pastDate": "هذا التاريخ مضى.",
  "public.pastDateNext": "اختر اليوم أو يوماً قادماً.",
  "public.hoursEnded": "لم تبق ساعات اليوم.",
  "public.hoursEndedNext": "اختر يوماً قادماً.",
  "public.langToEn": "EN",
  "public.langToAr": "ع",
  "public.langEnglish": "English",
  "public.langArabic": "العربية",
  "theme.label": "المظهر",
  "theme.light": "فاتح",
  "theme.dark": "داكن",
  "theme.system": "نظام",
  "public.errName": "أدخل الاسم.",
  "public.errPhone": "أدخل هاتفاً من 8 إلى 15 رقماً.",
  "public.cancelPolicy": "الإلغاء قبل أقل من {hours} من الموعد: رسوم {percent}% من السعر.",
  "dialog.close": "إغلاق",
  "login.title": "تسجيل الدخول",
  "login.identifier": "المعرّف",
  "login.password": "كلمة السر",
  "login.submit": "دخول",
  "owner.logout": "خروج",
  "owner.tabs": "الأقسام",
  "owner.home": "رئيسية",
  "owner.homeHeading": "الرئيسية",
  "owner.today": "اليوم",
  "owner.requests": "طلبات",
  "owner.upcoming": "القادم",
  "owner.upcomingTag": "قادم",
  "owner.overdue": "متأخر",
  "owner.showComingDays": "عرض الأيام القادمة",
  "owner.hideComingDays": "إخفاء الأيام القادمة",
  "owner.money": "المال",
  "owner.reports": "تقارير",
  "owner.more": "المزيد",
  "owner.requestsTab": "الطلبات",
  "owner.record": "تسجيل",
  "owner.recordBooking": "حجز",
  "owner.expenseAction": "مصروف",
  "owner.search": "بحث",
  "owner.searchPlaceholder": "اسم أو رقم",
  "owner.searchHint": "اكتب اسماً أو رقماً",
  "owner.searchEmpty": "لا أحد بهذا الاسم",
  "owner.searchEmptyNext": "جرّب اسماً آخر أو أرقام الهاتف",
  "owner.personGames": "المباريات",
  "owner.noPersonGames": "لا مباريات بعد",
  "owner.noPersonGamesNext": "مبارياته تظهر هنا",
  "owner.loadMore": "عرض المزيد",
  "owner.totalPaid": "المدفوع",
  "owner.owesNow": "عليه الآن",
  "owner.call": "اتصال",
  "owner.offline": "بدون اتصال",
  "owner.businessMenu": "قائمة العمل",
  "owner.publicPage": "صفحتي العامة",
  "owner.openPublic": "فتح",
  "owner.copyLink": "نسخ الرابط",
  "owner.copied": "تم النسخ",
  "owner.showQr": "إظهار الرمز",
  "owner.shareWhatsApp": "مشاركة عبر واتساب",
  "owner.account": "الحساب",
  "owner.back": "رجوع",
  "owner.groupBusiness": "العمل",
  "owner.groupPreferences": "التفضيلات",
  "owner.bookingRules": "قواعد الحجز",
  "owner.bookingRulesValue": "قبل الموعد",
  "owner.bookingRulesBody": "يمكن إلغاء الحجز قبل بداية الموعد ما دام المبلغ مستحقاً. لا نافذة ساعات محفوظة بعد.",
  "owner.updateRate": "تحديث السعر",
  "owner.justNow": "الآن",
  "owner.rateLastChanged": "آخر تغيير",
  "owner.shareWa": "واتساب",
  "owner.qrShort": "رمز",
  "owner.copyShort": "نسخ",
  "owner.appearance": "المظهر",
  "owner.language": "اللغة",
  "owner.identifier": "المعرّف",
  "owner.settings": "إعدادات",
  "owner.pending": "قيد الانتظار",
  "owner.confirmed": "مؤكد",
  "owner.requested": "طُلب",
  "owner.due": "مستحق",
  "owner.dueShort": "مستحق",
  "owner.leftShort": "متبقي",
  "owner.live": "مباشر",
  "owner.minLeft": "د متبقية",
  "owner.collect": "تحصيل",
  "owner.newRequests": "طلبات جديدة",
  "owner.remaining": "المتبقي",
  "owner.paid": "مدفوع",
  "owner.approve": "موافقة",
  "owner.hourJustBooked": "تم حجز هذه الساعة للتو",
  "owner.reject": "رفض",
  "owner.rejectSheet": "سبب الرفض",
  "owner.rejectConfirm": "تأكيد الرفض",
  "owner.rejectNote": "اكتب السبب",
  "owner.rejectReason.slotTaken": "الساعة محجوزة",
  "owner.rejectReason.pitchClosed": "الملعب مغلق",
  "owner.rejectReason.other": "سبب آخر",
  "owner.notifyConfirmed": "تم التأكيد",
  "owner.notifySheet": "إبلاغ",
  "owner.collectMixed": "دفع بعملتين",
  "owner.hideCollectMixed": "إخفاء الدفع بعملتين",
  "owner.usd": "دولار",
  "owner.usdRemaining": "المتبقي بالدولار",
  "owner.lbp": "ليرة",
  "owner.cancel": "إلغاء الحجز",
  "owner.cancelHint": "ستُلغى الساعة وتصبح متاحة مجدداً.",
  "owner.slotFree": "الساعة متاحة.",
  "owner.noOneWaiting": "لا أحد ينتظر هذه الساعة.",
  "owner.freeSlots": "ساعات متاحة فيها مهتمون",
  "owner.waitingSince": "ينتظر منذ",
  "owner.debtLead": "⚠ عليه",
  "owner.debtReason.LATE_CANCELLATION_FEE": "رسوم إلغاء",
  "owner.debtReason.NO_SHOW_FEE": "رسوم عدم الحضور",
  "owner.debtReason.CANCELLATION_NO_FEE": "إلغاء",
  "owner.debtReason.PARTIAL_GAME": "مباراة ناقصة",
  "owner.debtReason.DISCOUNT": "خصم",
  "owner.debtReason.WAIVER": "إعفاء",
  "owner.debtReason.CORRECTION": "تصحيح",
  "owner.yesterday": "أمس",
  "owner.collectedKeptTail": " ويبقى محفوظاً",
  "owner.notified": "تم الإبلاغ",
  "owner.playerCancelled": "اللاعب ألغى",
  "owner.ownerCancelled": "أنا ألغيت",
  "owner.editFee": "تعديل",
  "owner.waiveFee": "إعفاء",
  "owner.feeWord": "الرسوم",
  "owner.cancelledUnderHour": "ألغى قبل أقل من ساعة",
  "owner.noShowFeeLine": "لم يحضر",
  "owner.adjustDue": "تعديل المبلغ",
  "owner.newDue": "المبلغ الجديد",
  "owner.reasonDiscount": "خصم",
  "owner.reasonPartial": "مباراة ناقصة",
  "owner.reasonWaiver": "إعفاء",
  "owner.reasonCorrection": "تصحيح",
  "owner.noteOptional": "ملاحظة (اختياري)",
  "owner.saveRules": "حفظ",
  "owner.rulesTrailLead": "إلغاء",
  "owner.cancelWindow": "مهلة الإلغاء (ساعات)",
  "owner.lateFee": "رسوم الإلغاء المتأخر",
  "owner.noShowFeeSetting": "رسوم عدم الحضور",
  "owner.collectedPrefix": "تم تحصيل",
  "owner.noRefundYet": "، لا يمكن الاسترداد بعد.",
  "owner.cancelConfirm": "تأكيد إلغاء الحجز",
  "owner.cancelBack": "تراجع",
  "owner.noShow": "لم يحضر",
  "owner.toCollect": "للتحصيل",
  "owner.seeAll": "عرض الكل",
  "owner.prevDay": "اليوم السابق",
  "owner.nextDay": "اليوم التالي",
  "owner.monthCalendar": "الشهر",
  "owner.gamesWord": "مباريات",
  "owner.collectedWord": "محصّل",
  "owner.owedWord": "مستحق",
  "owner.expectedWord": "متوقع",
  "owner.noShowCount": "لم يحضر",
  "owner.noShowsCount": "لم يحضر",
  "owner.cancelledShort": "ملغى",
  "owner.bookHeading": "احجز ساعة",
  "owner.showSlots": "عرض الساعات",
  "owner.book": "احجز",
  "owner.waitlist": "قائمة الانتظار",
  "owner.waitlistTab": "انتظار",
  "owner.notify": "إبلاغ",
  "owner.notifyWhatsApp": "إبلاغ عبر واتساب",
  "owner.notifyGroup": "إبلاغ",
  "owner.moneyGroup": "تحصيل",
  "owner.openBooking": "عرض التفاصيل",
  "owner.period": "هذه الفترة",
  "owner.difference": "الفرق",
  "owner.in": "داخل",
  "owner.out": "خارج",
  "owner.from": "من",
  "owner.to": "إلى",
  "owner.view": "العرض",
  "owner.displayRate": "سعر العرض",
  "owner.show": "عرض",
  "owner.changePeriod": "تغيير الفترة",
  "owner.hidePeriod": "إخفاء الفترة",
  "owner.addExpense": "إضافة مصروف",
  "owner.hideExpenseForm": "إخفاء النموذج",
  "owner.rate": "سعر الصرف",
  "owner.noRate": "لم يُحدد سعر",
  "owner.newRate": "سعر جديد",
  "owner.setRate": "تعيين السعر",
  "owner.timeDisplay": "عرض الوقت",
  "owner.timeDisplayH23": "24 ساعة (16:00)",
  "owner.timeDisplayH12": "12 ساعة (4:00 PM)",
  "owner.setTimeDisplay": "حفظ",
  "owner.pitches": "الملاعب",
  "owner.pitchNew": "ملعب جديد",
  "owner.pitchEdit": "تعديل الملعب",
  "owner.pitchName": "الاسم",
  "owner.pitchOpen": "يفتح",
  "owner.pitchClose": "يغلق",
  "owner.pitchDuration": "مدة المباراة (دقائق)",
  "owner.pitchPrice": "السعر الافتراضي (دولار)",
  "owner.pitchPriceRules": "سعر حسب اليوم",
  "owner.pitchPriceRuleHint": "الصف الأخير يغلب إذا تداخلت الأيام.",
  "owner.pitchPriceRuleAdd": "إضافة سعر",
  "owner.pitchPriceRuleRemove": "حذف",
  "owner.pitchPriceRuleAmount": "السعر (دولار)",
  "owner.pitchHours": "ساعات الفتح",
  "owner.pitchHoursHint": "كل يوم في مجموعة واحدة. الأيام غير المختارة مغلقة.",
  "owner.pitchHoursAdd": "إضافة ساعات",
  "owner.pitchHoursRemove": "حذف",
  "owner.pitchClosed": "مغلق",
  "owner.pitchAllClosed": "مغلق كل الأيام.",
  "owner.wd.mon": "إثنين",
  "owner.wd.tue": "ثلاثاء",
  "owner.wd.wed": "أربعاء",
  "owner.wd.thu": "خميس",
  "owner.wd.fri": "جمعة",
  "owner.wd.sat": "سبت",
  "owner.wd.sun": "أحد",
  "owner.pitchSave": "حفظ الملعب",
  "owner.pitchCreate": "إضافة الملعب",
  "owner.pitchBack": "الإعدادات",
  "owner.pitchMinutes": "دق",
  "owner.pitchConfirmPending": "نعم، احفظ واترك الطلبات المعلّقة",
  "owner.expenses": "المصاريف",
  "owner.recordExpense": "تسجيل مصروف",
  "owner.category": "الفئة",
  "owner.what": "البيان",
  "owner.when": "التاريخ",
  "owner.recordExpenseSubmit": "تسجيل المصروف",
  "empty.pending": "لا طلبات معلّقة.",
  "empty.pendingNext": "عندما يطلب أحدهم ساعة، تظهر هنا.",
  "empty.confirmed": "لا مباريات مؤكدة اليوم.",
  "empty.confirmedNext": "الساعات الموافق عليها تظهر هنا.",
  "empty.pitches": "لا ملاعب بعد.",
  "empty.pitchesNext": "تظهر الملاعب هنا عندما يُدرجها هذا الملعب.",
  "empty.noCreate": "لا صلاحية للحجز.",
  "empty.noCreateNext": "هذه الصفحة للمالك أو لمن أُعطي صلاحية الحجز.",
  "empty.waitlist": "لا قائمة انتظار.",
  "empty.waitlistNext": "من طلب ساعة محجوزة يظهر هنا بعد الإلغاء.",
  "empty.expenses": "لا مصاريف بعد.",
  "empty.expensesNextRecord": "أضف مصروفاً بالزر أعلاه.",
  "empty.expensesNextStaff": "لا شيء في هذه القائمة.",
  "empty.noPitchEdit": "لا صلاحية لتعديل الملاعب.",
  "empty.noPitchEditNext": "هذه الصفحة للمالك.",
  "cat.ELECTRICITY": "كهرباء",
  "cat.WATER": "مياه",
  "cat.MAINTENANCE": "صيانة",
  "cat.SALARY": "راتب",
  "cat.EQUIPMENT": "تجهيزات",
  "cat.OTHER": "أخرى",
  "role.OWNER": "مالك",
  "role.STAFF": "موظف",
  lbpNote: "عيّن سعر عرض (أو عيّن سعر الصرف أولاً)",
};

const ENGLISH: Record<string, string> = {
  "doc.title": "Pitches",
  "public.day": "Day",
  "public.today": "Today",
  "public.tomorrow": "Tomorrow",
  "public.otherDate": "Other date",
  "public.showHours": "Show hours",
  "public.hours": "Hours",
  "public.taken": "Taken",
  "public.until": "until",
  "public.name": "Name",
  "public.phone": "Phone",
  "public.request": "Request",
  "public.emptyPitches": "No pitches yet.",
  "public.emptyPitchesNext": "This stadium has not listed pitches.",
  "public.closed": "Closed this day.",
  "public.closedNext": "Pick another day to see hours.",
  "public.pastDate": "This date has passed.",
  "public.pastDateNext": "Pick today or a coming day.",
  "public.hoursEnded": "No hours left today.",
  "public.hoursEndedNext": "Pick a coming day.",
  "public.langToEn": "EN",
  "public.langToAr": "ع",
  "public.langEnglish": "English",
  "public.langArabic": "العربية",
  "theme.label": "Theme",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "theme.system": "System",
  "public.errName": "Enter a name.",
  "public.errPhone": "Enter a phone with 8–15 digits.",
  "public.cancelPolicy": "Cancelling less than {hours} before the game costs {percent}% of the price.",
  "dialog.close": "Close",
  "login.title": "Log in",
  "login.identifier": "Identifier",
  "login.password": "Password",
  "login.submit": "Log in",
  "owner.logout": "Log out",
  "owner.tabs": "Sections",
  "owner.home": "Home",
  "owner.homeHeading": "Home",
  "owner.today": "Today",
  "owner.requests": "Requests",
  "owner.upcoming": "Upcoming",
  "owner.upcomingTag": "Upcoming",
  "owner.overdue": "Overdue",
  "owner.showComingDays": "Show coming days",
  "owner.hideComingDays": "Hide coming days",
  "owner.money": "Money",
  "owner.reports": "Reports",
  "owner.more": "More",
  "owner.requestsTab": "Requests",
  "owner.record": "Record",
  "owner.recordBooking": "Booking",
  "owner.expenseAction": "Expense",
  "owner.search": "Search",
  "owner.searchPlaceholder": "Name or number",
  "owner.searchHint": "Type a name or a number",
  "owner.searchEmpty": "No one matches",
  "owner.searchEmptyNext": "Try another name or the phone digits",
  "owner.personGames": "Games",
  "owner.noPersonGames": "No games yet",
  "owner.noPersonGamesNext": "Their games show here",
  "owner.loadMore": "Load more",
  "owner.totalPaid": "Paid",
  "owner.owesNow": "Owes now",
  "owner.call": "Call",
  "owner.offline": "Offline",
  "owner.businessMenu": "Business menu",
  "owner.publicPage": "My public page",
  "owner.openPublic": "Open",
  "owner.copyLink": "Copy link",
  "owner.copied": "Copied",
  "owner.showQr": "Show QR",
  "owner.shareWhatsApp": "Share on WhatsApp",
  "owner.account": "Account",
  "owner.back": "Back",
  "owner.groupBusiness": "Business",
  "owner.groupPreferences": "Preferences",
  "owner.bookingRules": "Booking rules",
  "owner.bookingRulesValue": "Before the slot",
  "owner.bookingRulesBody": "A booking can be cancelled before it starts while money is still due. No hours window is stored yet.",
  "owner.updateRate": "Update rate",
  "owner.justNow": "Just now",
  "owner.rateLastChanged": "Last changed",
  "owner.shareWa": "WhatsApp",
  "owner.qrShort": "QR",
  "owner.copyShort": "Copy",
  "owner.appearance": "Appearance",
  "owner.language": "Language",
  "owner.identifier": "Identifier",
  "owner.settings": "Settings",
  "owner.pending": "Pending",
  "owner.confirmed": "Confirmed",
  "owner.requested": "Requested",
  "owner.due": "Due",
  "owner.dueShort": "due",
  "owner.leftShort": "left",
  "owner.live": "Live",
  "owner.minLeft": "min left",
  "owner.collect": "Collect",
  "owner.newRequests": "new requests",
  "owner.remaining": "Remaining",
  "owner.paid": "Paid",
  "owner.approve": "Approve",
  "owner.hourJustBooked": "This hour was just booked",
  "owner.reject": "Reject",
  "owner.rejectSheet": "Reject reason",
  "owner.rejectConfirm": "Confirm reject",
  "owner.rejectNote": "Write the reason",
  "owner.rejectReason.slotTaken": "Slot taken",
  "owner.rejectReason.pitchClosed": "Pitch closed",
  "owner.rejectReason.other": "Other reason",
  "owner.notifyConfirmed": "Confirmed",
  "owner.notifySheet": "Notify",
  "owner.collectMixed": "Pay in two currencies",
  "owner.hideCollectMixed": "Hide two-currency pay",
  "owner.usd": "USD",
  "owner.usdRemaining": "Remaining USD",
  "owner.lbp": "LBP",
  "owner.cancel": "Cancel booking",
  "owner.cancelHint": "This hour will be freed and offered again.",
  "owner.slotFree": "The slot is available.",
  "owner.noOneWaiting": "No one is waiting for this slot.",
  "owner.freeSlots": "Available slots with interested players",
  "owner.waitingSince": "Waiting since",
  "owner.debtLead": "⚠ Owes",
  "owner.debtReason.LATE_CANCELLATION_FEE": "late cancellation",
  "owner.debtReason.NO_SHOW_FEE": "no-show fee",
  "owner.debtReason.CANCELLATION_NO_FEE": "cancellation",
  "owner.debtReason.PARTIAL_GAME": "partial game",
  "owner.debtReason.DISCOUNT": "discount",
  "owner.debtReason.WAIVER": "waiver",
  "owner.debtReason.CORRECTION": "correction",
  "owner.yesterday": "Yesterday",
  "owner.collectedKeptTail": " already collected is kept",
  "owner.notified": "Notified",
  "owner.playerCancelled": "Player cancelled",
  "owner.ownerCancelled": "I cancelled",
  "owner.editFee": "Edit",
  "owner.waiveFee": "Waive",
  "owner.feeWord": "Fee",
  "owner.cancelledUnderHour": "Cancelled less than an hour before",
  "owner.noShowFeeLine": "No-show",
  "owner.adjustDue": "Adjust amount",
  "owner.newDue": "New amount",
  "owner.reasonDiscount": "Discount",
  "owner.reasonPartial": "Partial game",
  "owner.reasonWaiver": "Waive",
  "owner.reasonCorrection": "Correction",
  "owner.noteOptional": "Note (optional)",
  "owner.saveRules": "Save",
  "owner.rulesTrailLead": "Cancel",
  "owner.cancelWindow": "Cancellation window (hours)",
  "owner.lateFee": "Late cancellation fee",
  "owner.noShowFeeSetting": "No-show fee",
  "owner.collectedPrefix": "Already collected",
  "owner.noRefundYet": ". Refunds are not supported yet.",
  "owner.cancelConfirm": "Confirm cancel booking",
  "owner.cancelBack": "Never mind",
  "owner.noShow": "No-show",
  "owner.toCollect": "To collect",
  "owner.seeAll": "See all",
  "owner.prevDay": "Previous day",
  "owner.nextDay": "Next day",
  "owner.monthCalendar": "Month",
  "owner.gamesWord": "games",
  "owner.collectedWord": "collected",
  "owner.owedWord": "owed",
  "owner.expectedWord": "expected",
  "owner.noShowCount": "no-show",
  "owner.noShowsCount": "no-shows",
  "owner.cancelledShort": "Cancelled",
  "owner.bookHeading": "Book an hour",
  "owner.showSlots": "Show hours",
  "owner.book": "Book",
  "owner.waitlist": "Waitlist",
  "owner.waitlistTab": "Waitlist",
  "owner.notify": "Notify",
  "owner.notifyWhatsApp": "Notify on WhatsApp",
  "owner.notifyGroup": "Notify",
  "owner.moneyGroup": "Collect",
  "owner.openBooking": "View details",
  "owner.period": "This period",
  "owner.difference": "Difference",
  "owner.in": "In",
  "owner.out": "Out",
  "owner.from": "From",
  "owner.to": "To",
  "owner.view": "View",
  "owner.displayRate": "Display rate",
  "owner.show": "Show",
  "owner.changePeriod": "Change period",
  "owner.hidePeriod": "Hide period",
  "owner.addExpense": "Add expense",
  "owner.hideExpenseForm": "Hide form",
  "owner.rate": "Exchange rate",
  "owner.noRate": "No rate set",
  "owner.newRate": "New rate",
  "owner.setRate": "Set rate",
  "owner.timeDisplay": "Time format",
  "owner.timeDisplayH23": "24-hour (16:00)",
  "owner.timeDisplayH12": "12-hour (4:00 PM)",
  "owner.setTimeDisplay": "Save",
  "owner.pitches": "Pitches",
  "owner.pitchNew": "New pitch",
  "owner.pitchEdit": "Edit pitch",
  "owner.pitchName": "Name",
  "owner.pitchOpen": "Opens",
  "owner.pitchClose": "Closes",
  "owner.pitchDuration": "Game length (minutes)",
  "owner.pitchPrice": "Default price (USD)",
  "owner.pitchPriceRules": "Day prices",
  "owner.pitchPriceRuleHint": "The last row wins when days overlap.",
  "owner.pitchPriceRuleAdd": "Add price",
  "owner.pitchPriceRuleRemove": "Remove",
  "owner.pitchPriceRuleAmount": "Price (USD)",
  "owner.pitchHours": "Opening hours",
  "owner.pitchHoursHint": "Each day belongs to one group. Unchecked days are closed.",
  "owner.pitchHoursAdd": "Add hours",
  "owner.pitchHoursRemove": "Remove",
  "owner.pitchClosed": "closed",
  "owner.pitchAllClosed": "Closed every day.",
  "owner.wd.mon": "Mon",
  "owner.wd.tue": "Tue",
  "owner.wd.wed": "Wed",
  "owner.wd.thu": "Thu",
  "owner.wd.fri": "Fri",
  "owner.wd.sat": "Sat",
  "owner.wd.sun": "Sun",
  "owner.pitchSave": "Save pitch",
  "owner.pitchCreate": "Add pitch",
  "owner.pitchBack": "Settings",
  "owner.pitchMinutes": "min",
  "owner.pitchConfirmPending": "Yes, save and leave pending requests as they are",
  "owner.expenses": "Expenses",
  "owner.recordExpense": "Record expense",
  "owner.category": "Category",
  "owner.what": "Description",
  "owner.when": "Date",
  "owner.recordExpenseSubmit": "Record expense",
  "empty.pending": "No pending requests.",
  "empty.pendingNext": "When someone requests an hour, it shows here.",
  "empty.confirmed": "No confirmed matches today.",
  "empty.confirmedNext": "Approved hours show here.",
  "empty.pitches": "No pitches yet.",
  "empty.pitchesNext": "Pitches show here when this stadium lists them.",
  "empty.noCreate": "No permission to book.",
  "empty.noCreateNext": "This page is for the owner or anyone given booking access.",
  "empty.waitlist": "No waitlist.",
  "empty.waitlistNext": "Anyone who requested a taken hour shows here after a cancel.",
  "empty.expenses": "No expenses yet.",
  "empty.expensesNextRecord": "Add an expense with the button above.",
  "empty.expensesNextStaff": "Nothing in this list.",
  "empty.noPitchEdit": "No permission to edit pitches.",
  "empty.noPitchEditNext": "This page is for the owner.",
  "cat.ELECTRICITY": "Electricity",
  "cat.WATER": "Water",
  "cat.MAINTENANCE": "Maintenance",
  "cat.SALARY": "Salary",
  "cat.EQUIPMENT": "Equipment",
  "cat.OTHER": "Other",
  "role.OWNER": "Owner",
  "role.STAFF": "Staff",
  lbpNote: "Set a display rate (or set the exchange rate first)",
};

/** Chrome for a key. Default Arabic. Missing English key falls back to Arabic. */
export function ui(key: string, locale: UiLocale = "ar"): string {
  if (locale === "en") return ENGLISH[key] ?? ARABIC[key] ?? key;
  return ARABIC[key] ?? key;
}

const REJECT_REASON_NOTE_MAX = 80;

/**
 * Chip label, or the free-text note for "other". Empty or too long → null.
 * The note is not stored; it only fills the WhatsApp {reason}.
 */
export function rejectReasonText(
  kind: string,
  note: string,
  locale: UiLocale = "ar",
): string | null {
  if (kind === "slot_taken") return ui("owner.rejectReason.slotTaken", locale);
  if (kind === "pitch_closed") return ui("owner.rejectReason.pitchClosed", locale);
  if (kind !== "other") return null;
  const text = note.trim().replace(/\s+/g, " ");
  if (!text || text.length > REJECT_REASON_NOTE_MAX) return null;
  return text;
}

/**
 * Counted nouns. `{n}` is the number. Arabic has every PluralRules category.
 * English has `one` and `other`; `zero` is optional for a count of 0.
 */
const COUNTED: Record<string, Record<UiLocale, PluralForms>> = {
  "owner.games": {
    ar: {
      zero: "لا مباريات",
      one: "مباراة واحدة",
      two: "مباراتان",
      few: "{n} مباريات",
      many: "{n} مباراة",
      other: "{n} مباراة",
    },
    en: {
      zero: "No games",
      one: "{n} game",
      other: "{n} games",
    },
  },
  "owner.interested": {
    ar: {
      zero: "لا مهتمين",
      one: "مهتم واحد",
      two: "مهتمان",
      few: "{n} مهتمين",
      many: "{n} مهتماً",
      other: "{n} مهتم",
    },
    en: {
      one: "{n} person interested",
      other: "{n} people interested",
    },
  },
  "owner.hoursBefore": {
    ar: {
      one: "ألغى قبل ساعة",
      two: "ألغى قبل ساعتين",
      few: "ألغى قبل {n} ساعات",
      many: "ألغى قبل {n} ساعة",
      other: "ألغى قبل {n} ساعة",
    },
    en: {
      one: "Cancelled {n} hour before",
      other: "Cancelled {n} hours before",
    },
  },
  "owner.ruleHours": {
    ar: {
      one: "ساعة",
      two: "ساعتين",
      few: "{n} ساعات",
      many: "{n} ساعة",
      other: "{n} ساعة",
    },
    en: {
      one: "{n} hour",
      other: "{n} hours",
    },
  },
  "owner.requests": {
    ar: {
      zero: "لا طلبات",
      one: "طلب واحد",
      two: "طلبان",
      few: "{n} طلبات",
      many: "{n} طلباً",
      other: "{n} طلب",
    },
    en: {
      zero: "No requests",
      one: "{n} request",
      other: "{n} requests",
    },
  },
  "owner.agoMinutes": {
    ar: {
      one: "قبل دقيقة",
      two: "قبل دقيقتين",
      few: "قبل {n} دقائق",
      many: "قبل {n} دقيقة",
      other: "قبل {n} دقيقة",
    },
    en: {
      one: "{n} minute ago",
      other: "{n} minutes ago",
    },
  },
  "owner.agoHours": {
    ar: {
      one: "قبل ساعة",
      two: "قبل ساعتين",
      few: "قبل {n} ساعات",
      many: "قبل {n} ساعة",
      other: "قبل {n} ساعة",
    },
    en: {
      one: "{n} hour ago",
      other: "{n} hours ago",
    },
  },
  "owner.agoDays": {
    ar: {
      two: "قبل يومين",
      few: "قبل {n} أيام",
      many: "قبل {n} يوماً",
      other: "قبل {n} يوم",
    },
    en: {
      other: "{n} days ago",
    },
  },
  "owner.noShows": {
    ar: {
      zero: "لا غيابات",
      one: "غياب واحد",
      two: "غيابان",
      few: "{n} غيابات",
      many: "{n} غياب",
      other: "{n} غياب",
    },
    en: {
      one: "{n} no-show",
      other: "{n} no-shows",
    },
  },
};

export function countedForms(key: string, locale: UiLocale): PluralForms | undefined {
  return COUNTED[key]?.[locale];
}

/** Counted noun for `locale`. Missing English forms fall back to Arabic rules. */
export function uiCount(key: string, count: number, locale: UiLocale = "ar"): string {
  const forms = COUNTED[key]?.[locale] ?? COUNTED[key]?.ar;
  if (!forms) return String(count);
  const rulesLocale = COUNTED[key]?.[locale] ? locale : "ar";
  return plural(rulesLocale, count, forms);
}

/** Empty hours: closed / past date / today exhausted. */
export function hoursEmptyState(
  kind: "closed" | "past" | "hoursEnded",
  locale: UiLocale = "ar",
): { title: string; next: string } {
  if (kind === "past") {
    return {
      title: ui("public.pastDate", locale),
      next: ui("public.pastDateNext", locale),
    };
  }
  if (kind === "hoursEnded") {
    return {
      title: ui("public.hoursEnded", locale),
      next: ui("public.hoursEndedNext", locale),
    };
  }
  return {
    title: ui("public.closed", locale),
    next: ui("public.closedNext", locale),
  };
}

/** Pending heading with a Western count. */
export function pendingCount(n: number, locale: UiLocale = "ar"): string {
  return `${ui("owner.pending", locale)} · ${n}`;
}

/** Requests heading. Digits stay inside the phrase so the caller can isolate them. */
export function requestsCount(n: number, locale: UiLocale = "ar"): string {
  return uiCount("owner.requests", n, locale);
}

/**
 * Public late-cancel line. Empty when the percent is 0.
 * `{hours}` is the plural hour phrase ("24 ساعة").
 */
export function cancelPolicyLine(
  hours: number,
  percent: number,
  locale: UiLocale = "ar",
): string {
  if (percent <= 0) return "";
  return ui("public.cancelPolicy", locale)
    .replace("{hours}", uiCount("owner.ruleHours", hours, locale))
    .replace("{percent}", String(percent));
}

/** Confirmed heading with a Western count. */
export function confirmedCount(n: number, locale: UiLocale = "ar"): string {
  return `${ui("owner.confirmed", locale)} · ${n}`;
}

/** Overdue heading with a Western count. */
export function overdueCount(n: number, locale: UiLocale = "ar"): string {
  return `${ui("owner.overdue", locale)} · ${n}`;
}

/** Collect remaining USD — amount is already formatUsd (Latin). */
export function collectUsdLabel(amount: string, locale: UiLocale = "ar"): string {
  return locale === "en" ? `Collect $${amount}` : `تحصيل $${amount}`;
}

/** Confirmed card due line. Amounts are already formatUsd (Latin). */
export function dueRemainingLine(
  due: string,
  remaining: string,
  locale: UiLocale = "ar",
): string {
  return locale === "en"
    ? `Due $${due} · remaining $${remaining}`
    : `المستحق $${due} · المتبقي $${remaining}`;
}

/** Exchange-rate card line. Amount is Latin digits, no currency symbol. */
export function lbpPerUsdLine(amount: string, locale: UiLocale = "ar"): string {
  return locale === "en"
    ? `${amount} LBP per USD`
    : `${amount} ليرة لكل دولار`;
}

/** Western thousands separator for a whole-number digit string. */
export function groupedDigits(digits: string): string {
  return digits.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

