import type { CopyArea } from "./types";

/** Account, login and permissions, push and WhatsApp notifications. */
export const account: CopyArea = {
  ar: {
    "owner.seriesWhatsApp": "أرسل التأكيد عبر واتساب",
    "push.newRequestTitle": "ملاعب",
    "push.newRequestOne": "طلب حجز جديد",
    "push.newRequestMany": "{n} طلبات بانتظارك",
    "owner.notifications": "الإشعارات",
    "push.working": "لحظة…",
    "push.unsupported": "هذا المتصفح لا يدعم الإشعارات.",
    "push.iosInstall": "أضف التطبيق إلى الشاشة الرئيسية أولاً: اضغط زر المشاركة، ثم «إضافة إلى الشاشة الرئيسية»، وافتحه من هناك.",
    "push.askBody": "فعّل الإشعارات ليصلك تنبيه على هذا الجهاز.",
    "push.enable": "تفعيل الإشعارات",
    "push.enabledStatus": "الإشعارات مفعّلة على هذا الجهاز.",
    "push.test": "إرسال إشعار تجريبي",
    "push.turnOff": "إيقاف",
    "push.deniedBody": "الإشعارات محظورة لهذا التطبيق. لتفعيلها: افتح إعدادات الهاتف، ثم إعدادات التطبيق أو المتصفح، ثم الإشعارات، وفعّلها.",
    "push.testSent": "أُرسل الإشعار. يجب أن يصل خلال لحظات.",
    "push.testNoDevice": "لا يوجد جهاز مفعّل لحسابك.",
    "push.testFailed": "تعذّر الوصول إلى هذا الجهاز. حاول مرة أخرى.",
    "push.turnedOff": "أُوقفت الإشعارات على هذا الجهاز.",
    "push.testTitle": "إشعار تجريبي",
    "push.testBody": "الإشعارات تعمل على هذا الجهاز.",
    "login.title": "تسجيل الدخول",
    "login.identifier": "المعرّف",
    "login.password": "كلمة السر",
    "login.submit": "دخول",
    "owner.logout": "خروج",
    "owner.account": "الحساب",
    "owner.changePassword": "تغيير كلمة المرور",
    "owner.changeLogin": "تغيير اسم الدخول",
    "owner.loginName": "اسم الدخول (الجزء قبل @)",
    "owner.loginWarning": "من الآن تسجّل الدخول بـ:",
    "owner.saveLogin": "حفظ اسم الدخول",
    "owner.loginChanged": "اسم الدخول الجديد:",
    "owner.currentPassword": "كلمة المرور الحالية",
    "owner.newPassword": "كلمة المرور الجديدة",
    "owner.passwordHint": "12 حرفاً أو أكثر. عبارة من عدة كلمات تكفي.",
    "owner.showPassword": "إظهار",
    "owner.hidePassword": "إخفاء",
    "owner.savePassword": "حفظ كلمة المرور",
    "owner.passwordChanged": "تم تغيير كلمة المرور. تم تسجيل الخروج من الأجهزة الأخرى.",
    "owner.logoutOthers": "تسجيل الخروج من الأجهزة الأخرى",
    "owner.logoutOthersAsk": "سيتم تسجيل الخروج من كل الأجهزة الأخرى. هذا الجهاز يبقى مسجلاً.",
    "owner.logoutOthersConfirm": "تسجيل الخروج الآن",
    "owner.shareWa": "واتساب",
    "owner.identifier": "المعرّف",
    "owner.notifyConfirmed": "تم التأكيد",
    "owner.notifySheet": "إبلاغ",
    "owner.notified": "تم الإبلاغ",
    "owner.notify": "إبلاغ",
    "owner.notifyWhatsApp": "إبلاغ عبر واتساب",
    "owner.notifyGroup": "إبلاغ",
    "owner.remindWhatsApp": "تذكير عبر واتساب",
    "role.OWNER": "مالك",
    "role.STAFF": "موظف",
  },
  en: {
    "owner.seriesWhatsApp": "Send the confirmation on WhatsApp",
    "push.newRequestTitle": "Lebstads",
    "push.newRequestOne": "New booking request",
    "push.newRequestMany": "{n} requests waiting",
    "owner.notifications": "Notifications",
    "push.working": "One moment…",
    "push.unsupported": "This browser does not support notifications.",
    "push.iosInstall": "Add the app to your Home Screen first: tap Share, then Add to Home Screen, and open it from there.",
    "push.askBody": "Turn on notifications to get an alert on this device.",
    "push.enable": "Enable notifications",
    "push.enabledStatus": "Notifications are on for this device.",
    "push.test": "Send a test notification",
    "push.turnOff": "Turn off",
    "push.deniedBody": "Notifications are blocked for this app. To allow them: open the phone's Settings, then the app's or browser's settings, then Notifications, and turn them on.",
    "push.testSent": "Sent. It should arrive in a moment.",
    "push.testNoDevice": "No device is turned on for your account.",
    "push.testFailed": "Could not reach this device. Try again.",
    "push.turnedOff": "Notifications are off on this device.",
    "push.testTitle": "Test notification",
    "push.testBody": "Notifications work on this device.",
    "login.title": "Log in",
    "login.identifier": "Identifier",
    "login.password": "Password",
    "login.submit": "Log in",
    "owner.logout": "Log out",
    "owner.account": "Account",
    "owner.changePassword": "Change password",
    "owner.changeLogin": "Change login",
    "owner.loginName": "Login name (the part before @)",
    "owner.loginWarning": "From now on you log in with:",
    "owner.saveLogin": "Save login",
    "owner.loginChanged": "Your login is now:",
    "owner.currentPassword": "Current password",
    "owner.newPassword": "New password",
    "owner.passwordHint": "12+ characters; a phrase works.",
    "owner.showPassword": "Show",
    "owner.hidePassword": "Hide",
    "owner.savePassword": "Save password",
    "owner.passwordChanged": "Password changed. Other devices were logged out.",
    "owner.logoutOthers": "Log out other devices",
    "owner.logoutOthersAsk": "Every other device will be logged out. This one stays logged in.",
    "owner.logoutOthersConfirm": "Log out now",
    "owner.shareWa": "WhatsApp",
    "owner.identifier": "Identifier",
    "owner.notifyConfirmed": "Confirmed",
    "owner.notifySheet": "Notify",
    "owner.notified": "Notified",
    "owner.notify": "Notify",
    "owner.notifyWhatsApp": "Notify on WhatsApp",
    "owner.notifyGroup": "Notify",
    "owner.remindWhatsApp": "Remind on WhatsApp",
    "role.OWNER": "Owner",
    "role.STAFF": "Staff",
  },
};
