import type { CopyArea } from "./types";

/** Shared owner chrome: tabs, navigation, weekday names, small verbs, unavailable notices. */
export const common: CopyArea = {
  ar: {
    "doc.title": "ملاعب",
    "dialog.close": "إغلاق",
    "owner.tabs": "الأقسام",
    "owner.home": "رئيسية",
    "owner.homeHeading": "الرئيسية",
    "owner.today": "اليوم",
    "owner.upcoming": "القادم",
    "owner.upcomingTag": "قادم",
    "owner.overdue": "متأخر",
    "owner.showComingDays": "عرض الأيام القادمة",
    "owner.hideComingDays": "إخفاء الأيام القادمة",
    "owner.more": "المزيد",
    "owner.record": "تسجيل",
    "owner.search": "بحث",
    "owner.searchPlaceholder": "اسم أو رقم",
    "owner.searchHint": "اكتب اسماً أو رقماً",
    "owner.searchEmpty": "لا أحد بهذا الاسم",
    "owner.searchEmptyNext": "جرّب اسماً آخر أو أرقام الهاتف",
    "owner.loadMore": "عرض المزيد",
    "owner.gameWord": "المباراة",
    "owner.shareWord": "الحصة",
    "owner.call": "اتصال",
    "owner.offline": "بدون اتصال",
    "owner.notNow": "ليس الآن",
    "owner.back": "رجوع",
    "owner.justNow": "الآن",
    "owner.print": "طباعة",
    "owner.qrShort": "رمز",
    "owner.copyShort": "نسخ",
    "owner.moreActions": "إجراءات أخرى",
    "owner.cancel": "إلغاء الحجز",
    "unavailable.owner.title": "الحساب موقوف مؤقتاً",
    "unavailable.owner.body": "لا يمكن استخدام هذا الحساب الآن. تواصل مع إدارة المنصة.",
    "owner.yesterday": "أمس",
    "owner.seeAll": "عرض الكل",
    "owner.nowLabel": "الآن",
    "owner.prevDay": "اليوم السابق",
    "owner.nextDay": "اليوم التالي",
    "owner.gamesWord": "مباريات",
    "owner.in": "داخل",
    "owner.out": "خارج",
    "owner.from": "من",
    "owner.to": "إلى",
    "owner.view": "العرض",
    "owner.show": "عرض",
    "owner.showMore": "عرض المزيد",
    "owner.dayFull.mon": "الإثنين",
    "owner.dayFull.tue": "الثلاثاء",
    "owner.dayFull.wed": "الأربعاء",
    "owner.dayFull.thu": "الخميس",
    "owner.dayFull.fri": "الجمعة",
    "owner.dayFull.sat": "السبت",
    "owner.dayFull.sun": "الأحد",
    "owner.wd.mon": "إثنين",
    "owner.wd.tue": "ثلاثاء",
    "owner.wd.wed": "أربعاء",
    "owner.wd.thu": "خميس",
    "owner.wd.fri": "جمعة",
    "owner.wd.sat": "سبت",
    "owner.wd.sun": "أحد",
  },
  en: {
    "doc.title": "Pitches",
    "dialog.close": "Close",
    "owner.tabs": "Sections",
    "owner.home": "Home",
    "owner.homeHeading": "Home",
    "owner.today": "Today",
    "owner.upcoming": "Upcoming",
    "owner.upcomingTag": "Upcoming",
    "owner.overdue": "Overdue",
    "owner.showComingDays": "Show coming days",
    "owner.hideComingDays": "Hide coming days",
    "owner.more": "More",
    "owner.record": "Record",
    "owner.search": "Search",
    "owner.searchPlaceholder": "Name or number",
    "owner.searchHint": "Type a name or a number",
    "owner.searchEmpty": "No one matches",
    "owner.searchEmptyNext": "Try another name or the phone digits",
    "owner.loadMore": "Load more",
    "owner.gameWord": "Game",
    "owner.shareWord": "Share",
    "owner.call": "Call",
    "owner.offline": "Offline",
    "owner.notNow": "Not now",
    "owner.back": "Back",
    "owner.justNow": "Just now",
    "owner.print": "Print",
    "owner.qrShort": "QR",
    "owner.copyShort": "Copy",
    "owner.moreActions": "More actions",
    "owner.cancel": "Cancel booking",
    "unavailable.owner.title": "Account temporarily suspended",
    "unavailable.owner.body": "This account can't be used right now. Please contact the platform team.",
    "owner.yesterday": "Yesterday",
    "owner.seeAll": "See all",
    "owner.nowLabel": "Now",
    "owner.prevDay": "Previous day",
    "owner.nextDay": "Next day",
    "owner.gamesWord": "games",
    "owner.in": "In",
    "owner.out": "Out",
    "owner.from": "From",
    "owner.to": "To",
    "owner.view": "View",
    "owner.show": "Show",
    "owner.showMore": "Show more",
    "owner.dayFull.mon": "Monday",
    "owner.dayFull.tue": "Tuesday",
    "owner.dayFull.wed": "Wednesday",
    "owner.dayFull.thu": "Thursday",
    "owner.dayFull.fri": "Friday",
    "owner.dayFull.sat": "Saturday",
    "owner.dayFull.sun": "Sunday",
    "owner.wd.mon": "Mon",
    "owner.wd.tue": "Tue",
    "owner.wd.wed": "Wed",
    "owner.wd.thu": "Thu",
    "owner.wd.fri": "Fri",
    "owner.wd.sat": "Sat",
    "owner.wd.sun": "Sun",
  },
};
