import type { UiLocale } from "@/lib/locale";

/**
 * Arabic copy for DomainError keys (DR-005). Keys stay (DR-004); next-intl later.
 * Unknown keys and legacy ?error=1 → generic.
 */
const ARABIC: Record<string, string> = {
  "booking.series_none": "تعذّر حجز أي أسبوع.",
  "booking.series_retry": "تغيّر الجدول أثناء الحفظ. حاول مرة أخرى.",
  "booking.series_not_found": "الحجز الثابت غير موجود.",
  "booking.series_exists": "هذا الحجز ثابت أصلاً.",
  "booking.changed": "تغيّر هذا الحجز. حدّث الصفحة وحاول مرة أخرى.",
  "booking.extend_not_approved": "يمكن تمديد المباريات المؤكدة فقط.",
  "booking.extend_ended": "انتهت هذه المباراة.",
  "booking.extend_per_player": "لا يمكن تمديد مباراة مقسّمة على اللاعبين.",
  "booking.extend_max": "الحد الأقصى ٣ ساعات.",
  "booking.extend_next_game": "هناك مباراة بعدها مباشرة.",
  "booking.extend_closing": "الملعب يغلق قبل ذلك.",
  "booking.extend_next_taken": "الوقت التالي محجوز.",
  "push.invalid_subscription": "تعذّر تفعيل الإشعارات على هذا الجهاز.",
  "push.not_configured": "الإشعارات غير مفعّلة على الخادم.",
  "push.rate_limited": "محاولات كثيرة. حاول مرة أخرى بعد قليل.",
  "error.generic": "حدث خطأ. حاول مرة أخرى.",
  "form.invalid": "راجع النموذج وحاول مرة أخرى.",
  "stadium.name_invalid": "اكتب اسم الملعب (حتى 60 حرفاً).",
  "stadium.address_invalid": "العنوان طويل. اجعله 120 حرفاً أو أقل.",
  "stadium.map_invalid": "رابط الخريطة غير مقبول. الصق رابطاً من خرائط Google يبدأ بـ https.",
  "stadium.phone_invalid": "اكتب رقماً لبنانياً صحيحاً، أرقاماً فقط.",
  "access.not_allowed": "لا يمكنك فعل ذلك.",
  "access.invalid_login": "تسجيل الدخول غير صالح.",
  "tenant.suspended": "هذه الخدمة غير متاحة مؤقتاً.",
  "access.login_throttled": "محاولات كثيرة. حاول مرة أخرى بعد 15 دقيقة.",
  "access.current_password_wrong": "كلمة المرور الحالية غير صحيحة.",
  "access.password_change_throttled": "محاولات كثيرة. حاول مرة أخرى بعد 15 دقيقة.",
  "access.password_too_short": "كلمة المرور قصيرة. استعمل 12 حرفاً على الأقل.",
  "access.password_same_as_identifier": "كلمة المرور لا يجوز أن تكون اسم الدخول أو اسم الملعب.",
  "access.password_denylisted": "كلمة المرور شائعة جداً. اختر عبارة أخرى.",
  "access.identifier_invalid": "اسم الدخول غير صالح. استعمل أحرفاً إنجليزية صغيرة وأرقاماً، وفاصلاً واحداً (. _ -) بين الأجزاء، حتى 32 حرفاً.",
  "access.identifier_taken": "اسم الدخول مستخدم. اختر غيره.",
  "shop.qty_invalid": "الكمية من 1 إلى 99.",
  "shop.product_not_found": "الصنف غير موجود.",
  "shop.product_unavailable": "أحد الأصناف لم يعد متاحاً للبيع.",
  "shop.sale_not_fully_paid": "يجب دفع كامل المبلغ.",
  "shop.sale_empty": "اختر صنفاً واحداً على الأقل.",
  "shop.rate_required": "حدّد سعر الصرف أولاً لبيع أصناف بالليرة.",
  "shop.booking_not_open": "يمكن إضافة الأصناف إلى مباراة مؤكدة فقط.",
  "shop.item_not_found": "هذا الصنف غير موجود على المباراة.",
  "shop.remove_exceeds": "لا يمكن إزالة أكثر من الكمية الموجودة.",
  "shop.tab_has_payments": "دُفع جزء من هذا الحساب، لا يمكن إزالة أصناف منه.",
  "shop.not_a_tab": "هذا ليس حساب لاعب.",
  "shop.player_not_found": "اللاعب غير موجود.",
  "booking.not_found": "الحجز غير موجود.",
  "booking.pending_only": "يمكن الموافقة على طلب معلّق أو رفضه فقط.",
  "booking.no_longer_pending": "تم حجز هذه الساعة للتو",
  "booking.confirmed_only": "يمكن إلغاء حجز مؤكد فقط.",
  "booking.cancel_started": "لا يمكن إلغاء مباراة بدأت. إذا لم تحدث، سجّل «لم يحضر».",
  "booking.no_show_only_approved": "يمكن تسجيل عدم الحضور لحجز مؤكد فقط.",
  "booking.no_show_not_ended":
    "يمكن تسجيل عدم الحضور بعد انتهاء الساعة فقط.",
  "booking.slot_not_offered": "هذه الساعة غير معروضة.",
  "booking.slot_taken": "هذه الساعة محجوزة.",
  "booking.request_limit": "لا يمكن إرسال طلبات أخرى الآن. حاول لاحقاً أو اتصل بالملعب.",
  "booking.slot_taken_noted": "هذه الساعة حُجزت. سجّلنا اهتمامك وسنبلغك إذا صارت متاحة.",
  "booking.slot_ended": "هذه الساعة انتهت.",
  "booking.too_far": "لا يمكن طلب موعد بعيد إلى هذا الحد. اختر يوماً أقرب.",
  "booking.slot_unavailable": "الساعة لم تعد متاحة.",
  "booking.pitch_not_found": "الملعب غير موجود.",
  "booking.requester_not_found": "صاحب الطلب غير موجود.",
  "booking.switch_fee_booking": "لا يمكن تقسيم رسوم حجز ملغى أو لم يحدث على اللاعبين.",
  "booking.switch_not_approved": "التقسيم متاح للحجز المؤكد فقط.",
  "booking.switch_not_whole": "الحجز مقسّم على اللاعبين مسبقًا.",
  "booking.switch_no_due": "لا يوجد مبلغ لتقسيمه.",
  "booking.switch_not_per_player": "الحجز ليس مقسّمًا على اللاعبين.",
  "booking.switch_has_allocations": "لا يمكن العودة للحجز الكامل بعد تسجيل دفعات اللاعبين.",
  "booking.collect_per_player": "الحجز مقسّم على اللاعبين. سجّل الدفع لكل لاعب.",
  "booking.split_disabled": "تقسيم الدفع بين اللاعبين غير مفعّل. فعّله من قواعد الحجز.",
  "booking.split_count": "عدد اللاعبين يجب أن يكون بين ١ و٣٠.",
  "booking.due_negative": "المبلغ المستحق لا يمكن أن يكون أقل من صفر.",
  "booking.due_below_collected":
    "تم تحصيل مبلغ أكبر من الجديد، لا يمكن الاسترداد بعد.",
  "booking.due_whole_only": "تعديل المبلغ متاح للحجز الكامل فقط.",
  "booking.fee_above_due": "الرسوم لا يمكن أن تكون أكثر من المبلغ المستحق على الحجز.",
  "booking.due_not_confirmed": "تعديل المبلغ متاح لحجز مؤكد أو ملغى أو لم يحضر فقط.",
  "payment.collect_unapproved": "يمكن التحصيل من حجز مؤكد أو لم يحضر أو ملغى فقط.",
  "payment.nothing_due": "لا يوجد مبلغ مستحق.",
  "payment.rate_required": "عيّن سعر الصرف أولاً.",
  "payment.amount_required": "المبلغ مطلوب.",
  "payment.amount_positive": "يجب أن يكون المبلغ أكبر من صفر.",
  "notification.bad_phone": "لا يمكن استخدام هذا الرقم لواتساب.",
  "ledger.invalid_period": "الفترة غير صالحة.",
  "expense.invalid_date": "تاريخ المصروف غير صالح.",
  "venue.hours_approved":
    "لا يمكن تقليص الساعات: هناك حجز مؤكد في الوقت المحذوف.",
  "venue.hours_pending":
    "هناك طلب معلّق في ساعات ستُحذف. أكّد للحفظ دون رفض الطلب.",
  "venue.hours_day_overlap": "لا يمكن وضع نفس اليوم في مجموعتي ساعات.",
};

const ENGLISH: Record<string, string> = {
  "booking.series_none": "No week could be booked.",
  "booking.series_retry": "The schedule changed while saving. Try again.",
  "booking.series_not_found": "Weekly booking not found.",
  "booking.series_exists": "This booking is already weekly.",
  "booking.changed": "This booking changed. Refresh and try again.",
  "booking.extend_not_approved": "Only confirmed games can be extended.",
  "booking.extend_ended": "This game has ended.",
  "booking.extend_per_player": "A game split per player cannot be extended.",
  "booking.extend_max": "Maximum 3 hours.",
  "booking.extend_next_game": "There is a game right after it.",
  "booking.extend_closing": "The pitch closes before that.",
  "booking.extend_next_taken": "The next time is taken.",
  "push.invalid_subscription": "Could not turn on notifications on this device.",
  "push.not_configured": "Notifications are not set up on the server.",
  "push.rate_limited": "Too many tries. Try again in a few minutes.",
  "error.generic": "Something went wrong. Try again.",
  "form.invalid": "Check the form and try again.",
  "stadium.name_invalid": "Enter the stadium name (up to 60 characters).",
  "stadium.address_invalid": "The address is too long. Keep it to 120 characters.",
  "stadium.map_invalid": "That map link is not accepted. Paste a Google Maps link that starts with https.",
  "stadium.phone_invalid": "Enter a valid Lebanese number, digits only.",
  "access.not_allowed": "You are not allowed to do that.",
  "access.invalid_login": "Invalid login.",
  "tenant.suspended": "This service is temporarily unavailable.",
  "access.login_throttled": "Too many attempts. Try again in 15 minutes.",
  "access.current_password_wrong": "The current password is not correct.",
  "access.password_change_throttled": "Too many attempts. Try again in 15 minutes.",
  "access.password_too_short": "That password is too short. Use at least 12 characters.",
  "access.password_same_as_identifier": "The password cannot be your login or the stadium name.",
  "access.password_denylisted": "That password is too common. Pick a different phrase.",
  "access.identifier_invalid": "That login is not allowed. Use lowercase letters and digits, one separator (. _ -) between parts, up to 32 characters.",
  "access.identifier_taken": "That login is already taken. Pick another.",
  "shop.qty_invalid": "Quantity must be from 1 to 99.",
  "shop.product_not_found": "That item does not exist.",
  "shop.product_unavailable": "An item is no longer available to sell.",
  "shop.sale_not_fully_paid": "A sale must be paid in full.",
  "shop.sale_empty": "Pick at least one item.",
  "shop.rate_required": "Set the exchange rate first to sell items priced in LBP.",
  "shop.booking_not_open": "Items can only go on a confirmed game.",
  "shop.item_not_found": "That item is not on the game.",
  "shop.remove_exceeds": "You cannot remove more than is there.",
  "shop.tab_has_payments": "Part of this tab is paid, so items cannot be removed from it.",
  "shop.not_a_tab": "That is not a player's tab.",
  "shop.player_not_found": "That player does not exist.",
  "booking.not_found": "Booking not found.",
  "booking.pending_only": "Only a pending request can be approved or rejected.",
  "booking.no_longer_pending": "This hour was just booked",
  "booking.confirmed_only": "Only a confirmed booking can be cancelled.",
  "booking.cancel_started":
    "A game that has started can't be cancelled. If it didn't happen, record a no-show.",
  "booking.no_show_only_approved":
    "Only a confirmed booking can be marked no-show.",
  "booking.no_show_not_ended":
    "A no-show can be recorded only after the hour has ended.",
  "booking.slot_not_offered": "That hour is not offered.",
  "booking.slot_taken": "That hour is taken.",
  "booking.request_limit": "No more requests can be sent right now. Try again later or call the stadium.",
  "booking.slot_taken_noted":
    "That hour was just booked. We noted your interest and will tell you if it frees up.",
  "booking.slot_ended": "That hour has ended.",
  "booking.too_far": "That day is too far ahead to request. Pick a closer day.",
  "booking.slot_unavailable": "The hour is no longer available.",
  "booking.pitch_not_found": "Pitch not found.",
  "booking.requester_not_found": "Requester not found.",
  "booking.switch_fee_booking": "A cancelled or no-show fee can't be split among players.",
  "booking.switch_not_approved": "Only a confirmed booking can be split among players.",
  "booking.switch_not_whole": "This booking is already split among players.",
  "booking.switch_no_due": "Nothing is due to split.",
  "booking.switch_not_per_player": "This booking isn't split among players.",
  "booking.switch_has_allocations": "Can't go back to whole game once player payments are recorded.",
  "booking.collect_per_player": "This booking is split per player. Record payment per player.",
  "booking.split_disabled": "Per-player split is turned off. Turn it on in Booking rules.",
  "booking.split_count": "Player count must be between 1 and 30.",
  "booking.due_negative": "The amount due cannot be below zero.",
  "booking.due_below_collected":
    "Already collected more than the new amount. Refunds are not supported yet.",
  "booking.due_whole_only": "Adjusting the due is only available for a whole-game booking.",
  "booking.fee_above_due": "The fee can't be more than what the booking owes.",
  "booking.due_not_confirmed":
    "Only a confirmed, cancelled, or no-show booking can have its due adjusted.",
  "payment.collect_unapproved": "Only a confirmed, no-show, or cancelled booking can be collected.",
  "payment.nothing_due": "Nothing is due.",
  "payment.rate_required": "Set the exchange rate first.",
  "payment.amount_required": "An amount is required.",
  "payment.amount_positive": "Amount must be greater than zero.",
  "notification.bad_phone": "That number cannot be used for WhatsApp.",
  "ledger.invalid_period": "That period is not valid.",
  "expense.invalid_date": "That expense date is not valid.",
  "venue.hours_approved":
    "Cannot shrink hours: an approved booking sits in a removed window.",
  "venue.hours_pending":
    "A pending request sits in hours you are removing. Confirm to save without rejecting it.",
  "venue.hours_day_overlap": "A day cannot be in two hours groups.",
};

/** Owner-facing copy for a key. Never returns a stack or Prisma dump. */
export function errorMessage(key: string, locale: UiLocale = "ar"): string {
  if (key === "1") {
    return locale === "en" ? ENGLISH["error.generic"]! : ARABIC["error.generic"]!;
  }
  if (locale === "en") return ENGLISH[key] ?? ARABIC[key] ?? ENGLISH["error.generic"]!;
  return ARABIC[key] ?? ARABIC["error.generic"]!;
}
