import type { CopyArea } from "./types";

/** Money: payments and tenders, fees and due changes, the Money page, expenses and categories. */
export const money: CopyArea = {
  ar: {
    "owner.money": "المال",
    "owner.reports": "تقارير",
    "owner.expenseAction": "مصروف",
    "owner.totalPaid": "إجمالي المدفوع",
    "owner.expectedLabel": "متوقع",
    "owner.owedLabel": "مستحق",
    "owner.owesNow": "عليه الآن",
    "owner.updateRate": "تحديث السعر",
    "owner.rateLastChanged": "آخر تغيير",
    "owner.due": "مستحق",
    "owner.dueShort": "مستحق",
    "owner.leftShort": "متبقي",
    "owner.collect": "تحصيل",
    "owner.remaining": "المتبقي",
    "owner.paid": "مدفوع",
    "owner.collectMixed": "دفع بعملتين",
    "owner.payAnotherWay": "الدفع بطريقة أخرى (ليرة، جزئي)",
    "owner.usd": "دولار",
    "owner.usdRemaining": "المتبقي بالدولار",
    "owner.modeWhole": "الحجز كامل",
    "owner.modePerPlayer": "لكل لاعب",
    "owner.modeLabel": "طريقة التحصيل",
    "owner.playerCount": "عدد اللاعبين",
    "owner.splitConfirm": "قسّم",
    "owner.payPlayer": "دفع",
    "owner.slotPaid": "دفع",
    "owner.slotCovered": "مغطّى بدفعة سابقة",
    "owner.unassigned": "غير مخصّص",
    "owner.perPlayerLocked": "لا يمكن العودة للحجز الكامل بعد تسجيل دفعات اللاعبين.",
    "owner.lbp": "ليرة",
    "owner.tenderTotal": "المجموع",
    "owner.tenderStillDue": "الباقي لإكمال المبلغ",
    "owner.tenderPaidInFull": "المبلغ مكتمل",
    "owner.tenderOver": "أكثر من المطلوب بـ",
    "owner.tenderFillLbp": "أكمل بـ",
    "owner.tenderBadUsd": "اكتب الدولار مثل 20 أو 20.50",
    "owner.tenderBadLbp": "اكتب الليرة أرقاماً فقط، بلا فواصل",
    "owner.debtLead": "⚠ عليه",
    "owner.debtReason.LATE_CANCELLATION_FEE": "رسوم إلغاء",
    "owner.debtReason.NO_SHOW_FEE": "رسوم عدم الحضور",
    "owner.debtReason.CANCELLATION_NO_FEE": "إلغاء",
    "owner.debtReason.PARTIAL_GAME": "مباراة ناقصة",
    "owner.debtReason.DISCOUNT": "خصم",
    "owner.debtReason.WAIVER": "إعفاء",
    "owner.debtReason.CORRECTION": "تصحيح",
    "owner.collectedKeptTail": " ويبقى محفوظاً",
    "owner.editFee": "تعديل",
    "owner.waiveFee": "إعفاء",
    "owner.feeWord": "الرسوم",
    "owner.cancelledUnderHour": "ألغى قبل أقل من ساعة",
    "owner.noShowFeeLine": "لم يحضر",
    "owner.adjustDue": "تعديل المبلغ",
    "owner.newDue": "المبلغ الجديد",
    "owner.reasonDiscount": "خصم",
    "owner.reasonPartial": "مباراة ناقصة",
    "owner.reasonWaiver": "إعفاء",
    "owner.reasonCorrection": "تصحيح",
    "owner.noteOptional": "ملاحظة (اختياري)",
    "owner.collectedPrefix": "تم تحصيل",
    "owner.noRefundYet": "، لا يمكن الاسترداد بعد.",
    "owner.toCollect": "للتحصيل",
    "owner.owedFromEarlier": "مستحق من أيام سابقة",
    "owner.collectedWord": "محصّل",
    "owner.owedWord": "مستحق",
    "owner.expectedWord": "متوقع",
    "owner.noShowCount": "لم يحضر",
    "owner.noShowsCount": "لم يحضر",
    "owner.moneyGroup": "تحصيل",
    "owner.period": "هذه الفترة",
    "owner.difference": "الفرق",
    "owner.net": "الصافي = الداخل − الخارج",
    "owner.displayRate": "سعر العرض",
    "owner.changePeriod": "تغيير الفترة",
    "owner.periodTitle": "الفترة",
    "owner.owedToYou": "مستحق لك",
    "owner.owedTitle": "مستحق لك",
    "owner.owedNone": "لا أحد مدين لك.",
    "owner.owedNoneNext": "المبالغ غير المدفوعة من المباريات المنتهية تظهر هنا.",
    "owner.unnamedPlayers": "لاعبون بلا أسماء",
    "owner.unnamedPlayer": "لاعب بلا اسم",
    "empty.noReports": "لا صلاحية لعرض التقارير.",
    "empty.noReportsNext": "اطلب من المالك أن يمنحك صلاحية التقارير.",
    "owner.activity": "النشاط",
    "owner.activityAll": "الكل",
    "owner.activityEmpty": "لا حركة في هذه الفترة.",
    "owner.activityGame": "مباراة",
    "owner.sourceGames": "مباريات",
    "owner.recentActivity": "آخر الحركات",
    "owner.allActivity": "كل الحركات",
    "owner.expensePlus": "+ مصروف",
    "owner.cashToday": "النقد اليوم",
    "owner.cashNet": "الصافي",
    "owner.cashTodayNote": "الأوراق والعملات التي تغيّر مكانها في يوم العمل هذا، كل عملة على حدة. ليست قيمة ولا تدخل في المجاميع.",
    "owner.activityPlayer": "لاعب",
    "owner.activityExpense": "مصروف",
    "owner.activityGeneric": "حركة",
    "owner.expenseAmount": "المبلغ",
    "owner.expenseCategory": "الفئة",
    "owner.expenseDate": "التاريخ",
    "owner.paidWith": "الدفع",
    "owner.periodToday": "اليوم",
    "owner.periodWeek": "هذا الأسبوع",
    "owner.periodMonth": "هذا الشهر",
    "owner.periodLast": "الشهر الماضي",
    "owner.periodCustom": "فترة محددة",
    "owner.vsPrevious": "الفترة السابقة",
    "owner.hidePeriod": "إخفاء الفترة",
    "owner.addExpense": "إضافة مصروف",
    "owner.hideExpenseForm": "إخفاء النموذج",
    "owner.rate": "سعر الصرف",
    "owner.noRate": "لم يُحدد سعر",
    "owner.newRate": "سعر جديد",
    "owner.setRate": "تعيين السعر",
    "owner.expenses": "المصاريف",
    "owner.recordExpense": "تسجيل مصروف",
    "owner.category": "الفئة",
    "owner.what": "البيان",
    "owner.when": "التاريخ",
    "owner.recordExpenseSubmit": "تسجيل المصروف",
    "empty.expenses": "لا مصاريف بعد.",
    "empty.expensesNextRecord": "أضف مصروفاً بالزر أعلاه.",
    "empty.expensesNextStaff": "لا شيء في هذه القائمة.",
    "cat.ELECTRICITY": "كهرباء",
    "cat.WATER": "مياه",
    "cat.MAINTENANCE": "صيانة",
    "cat.SALARY": "راتب",
    "cat.EQUIPMENT": "تجهيزات",
    "cat.OTHER": "أخرى",
    "cat.SHOP_SUPPLIES": "بضاعة المتجر",
  },
  en: {
    "owner.money": "Money",
    "owner.reports": "Reports",
    "owner.expenseAction": "Expense",
    "owner.totalPaid": "Total paid",
    "owner.expectedLabel": "Expected",
    "owner.owedLabel": "Owed",
    "owner.owesNow": "Owes now",
    "owner.updateRate": "Update rate",
    "owner.rateLastChanged": "Last changed",
    "owner.due": "Due",
    "owner.dueShort": "due",
    "owner.leftShort": "left",
    "owner.collect": "Collect",
    "owner.remaining": "Remaining",
    "owner.paid": "Paid",
    "owner.collectMixed": "Pay in two currencies",
    "owner.payAnotherWay": "Pay another way (LBP, partial)",
    "owner.usd": "USD",
    "owner.usdRemaining": "Remaining USD",
    "owner.modeWhole": "Whole game",
    "owner.modePerPlayer": "Per player",
    "owner.modeLabel": "How to collect",
    "owner.playerCount": "Players",
    "owner.splitConfirm": "Split",
    "owner.payPlayer": "Pay",
    "owner.slotPaid": "Paid",
    "owner.slotCovered": "Covered by earlier payment",
    "owner.unassigned": "Unassigned",
    "owner.perPlayerLocked": "Can't go back to whole game once player payments are recorded.",
    "owner.lbp": "LBP",
    "owner.tenderTotal": "Total",
    "owner.tenderStillDue": "Left to complete",
    "owner.tenderPaidInFull": "Covers the full amount",
    "owner.tenderOver": "More than due by",
    "owner.tenderFillLbp": "Complete with",
    "owner.tenderBadUsd": "Type USD like 20 or 20.50",
    "owner.tenderBadLbp": "Type LBP as digits only, no commas",
    "owner.debtLead": "⚠ Owes",
    "owner.debtReason.LATE_CANCELLATION_FEE": "late cancellation",
    "owner.debtReason.NO_SHOW_FEE": "no-show fee",
    "owner.debtReason.CANCELLATION_NO_FEE": "cancellation",
    "owner.debtReason.PARTIAL_GAME": "partial game",
    "owner.debtReason.DISCOUNT": "discount",
    "owner.debtReason.WAIVER": "waiver",
    "owner.debtReason.CORRECTION": "correction",
    "owner.collectedKeptTail": " already collected is kept",
    "owner.editFee": "Edit",
    "owner.waiveFee": "Waive",
    "owner.feeWord": "Fee",
    "owner.cancelledUnderHour": "Cancelled less than an hour before",
    "owner.noShowFeeLine": "No-show",
    "owner.adjustDue": "Adjust amount",
    "owner.newDue": "New amount",
    "owner.reasonDiscount": "Discount",
    "owner.reasonPartial": "Partial game",
    "owner.reasonWaiver": "Waive",
    "owner.reasonCorrection": "Correction",
    "owner.noteOptional": "Note (optional)",
    "owner.collectedPrefix": "Already collected",
    "owner.noRefundYet": ". Refunds are not supported yet.",
    "owner.toCollect": "To collect",
    "owner.owedFromEarlier": "owed from earlier days",
    "owner.collectedWord": "collected",
    "owner.owedWord": "owed",
    "owner.expectedWord": "expected",
    "owner.noShowCount": "no-show",
    "owner.noShowsCount": "no-shows",
    "owner.moneyGroup": "Collect",
    "owner.period": "This period",
    "owner.difference": "Difference",
    "owner.net": "Net = in − out",
    "owner.displayRate": "Display rate",
    "owner.changePeriod": "Change period",
    "owner.periodTitle": "Period",
    "owner.owedToYou": "Owed to you",
    "owner.owedTitle": "Owed to you",
    "owner.owedNone": "Nobody owes you anything.",
    "owner.owedNoneNext": "Unpaid money from games that have ended shows here.",
    "owner.unnamedPlayers": "Unnamed players",
    "owner.unnamedPlayer": "Unnamed player",
    "empty.noReports": "You cannot view reports.",
    "empty.noReportsNext": "Ask the owner to give you the reports permission.",
    "owner.activity": "Activity",
    "owner.activityAll": "All",
    "owner.activityEmpty": "Nothing moved in this period.",
    "owner.activityGame": "Game",
    "owner.sourceGames": "Games",
    "owner.recentActivity": "Recent activity",
    "owner.allActivity": "All activity",
    "owner.expensePlus": "+ Expense",
    "owner.cashToday": "Cash today",
    "owner.cashNet": "Net",
    "owner.cashTodayNote": "Notes and coins that changed hands in this business day, each currency on its own. Not a value and not part of the totals.",
    "owner.activityPlayer": "Player",
    "owner.activityExpense": "Expense",
    "owner.activityGeneric": "Payment",
    "owner.expenseAmount": "Amount",
    "owner.expenseCategory": "Category",
    "owner.expenseDate": "Date",
    "owner.paidWith": "Paid with",
    "owner.periodToday": "Today",
    "owner.periodWeek": "This week",
    "owner.periodMonth": "This month",
    "owner.periodLast": "Last month",
    "owner.periodCustom": "Custom",
    "owner.vsPrevious": "the previous period",
    "owner.hidePeriod": "Hide period",
    "owner.addExpense": "Add expense",
    "owner.hideExpenseForm": "Hide form",
    "owner.rate": "Exchange rate",
    "owner.noRate": "No rate set",
    "owner.newRate": "New rate",
    "owner.setRate": "Set rate",
    "owner.expenses": "Expenses",
    "owner.recordExpense": "Record expense",
    "owner.category": "Category",
    "owner.what": "Description",
    "owner.when": "Date",
    "owner.recordExpenseSubmit": "Record expense",
    "empty.expenses": "No expenses yet.",
    "empty.expensesNextRecord": "Add an expense with the button above.",
    "empty.expensesNextStaff": "Nothing in this list.",
    "cat.ELECTRICITY": "Electricity",
    "cat.WATER": "Water",
    "cat.MAINTENANCE": "Maintenance",
    "cat.SALARY": "Salary",
    "cat.EQUIPMENT": "Equipment",
    "cat.OTHER": "Other",
    "cat.SHOP_SUPPLIES": "Shop supplies",
  },
};
