import type { CopyArea } from "./types";

/** The public stadium page a player sees. */
export const publicPage: CopyArea = {
  ar: {
    "public.day": "اليوم",
    "public.today": "اليوم",
    "public.tomorrow": "غداً",
    "public.otherDate": "تاريخ آخر",
    "public.showHours": "عرض الساعات",
    "public.hours": "الساعات",
    "public.taken": "محجوز",
    "public.until": "حتى",
    "public.name": "الاسم",
    "public.phone": "الهاتف",
    "public.request": "اطلب",
    "public.emptyPitches": "لا ملاعب بعد.",
    "public.emptyPitchesNext": "هذا الملعب لم يُدرج ملاعب.",
    "public.closed": "مغلق هذا اليوم.",
    "public.closedNext": "اختر يوماً آخر لرؤية الساعات.",
    "public.pastDate": "هذا التاريخ مضى.",
    "public.pastDateNext": "اختر اليوم أو يوماً قادماً.",
    "public.hoursEnded": "لم تبق ساعات اليوم.",
    "public.hoursEndedNext": "اختر يوماً قادماً.",
    "public.langToEn": "EN",
    "public.langToAr": "ع",
    "public.langEnglish": "English",
    "public.langArabic": "العربية",
    "public.errName": "أدخل الاسم.",
    "public.errPhone": "أدخل هاتفاً من 8 إلى 15 رقماً.",
    "public.cancelPolicy": "الإلغاء قبل أقل من {hours} من الموعد: رسوم {percent}% من السعر.",
    "public.openInMaps": "افتح في الخريطة",
    "public.call": "اتصل",
    "public.whatsapp": "واتساب",
    "public.poweredBy": "مدعوم من lebstads",
    "unavailable.public.title": "غير متاح مؤقتاً",
    "unavailable.public.body": "هذه الصفحة غير متاحة الآن. حاول مرة أخرى لاحقاً.",
  },
  en: {
    "public.day": "Day",
    "public.today": "Today",
    "public.tomorrow": "Tomorrow",
    "public.otherDate": "Other date",
    "public.showHours": "Show hours",
    "public.hours": "Hours",
    "public.taken": "Taken",
    "public.until": "until",
    "public.name": "Name",
    "public.phone": "Phone",
    "public.request": "Request",
    "public.emptyPitches": "No pitches yet.",
    "public.emptyPitchesNext": "This stadium has not listed pitches.",
    "public.closed": "Closed this day.",
    "public.closedNext": "Pick another day to see hours.",
    "public.pastDate": "This date has passed.",
    "public.pastDateNext": "Pick today or a coming day.",
    "public.hoursEnded": "No hours left today.",
    "public.hoursEndedNext": "Pick a coming day.",
    "public.langToEn": "EN",
    "public.langToAr": "ع",
    "public.langEnglish": "English",
    "public.langArabic": "العربية",
    "public.errName": "Enter a name.",
    "public.errPhone": "Enter a phone with 8–15 digits.",
    "public.cancelPolicy": "Cancelling less than {hours} before the game costs {percent}% of the price.",
    "public.openInMaps": "Open in Maps",
    "public.call": "Call",
    "public.whatsapp": "WhatsApp",
    "public.poweredBy": "Powered by lebstads",
    "unavailable.public.title": "Temporarily unavailable",
    "unavailable.public.body": "This page is not available right now. Please try again later.",
  },
};
