import type { CopyArea } from "./types";

/** Requests and the waitlist: approve, reject, dismiss. */
export const requests: CopyArea = {
  ar: {
    "owner.requests": "طلبات",
    "owner.requestsTab": "الطلبات",
    "owner.pending": "قيد الانتظار",
    "owner.requested": "طُلب",
    "owner.newRequests": "طلبات جديدة",
    "owner.approve": "موافقة",
    "owner.theyPlayed": "لعبوا فعلاً",
    "owner.dismiss": "تجاهل",
    "owner.dismissAll": "تجاهل الكل",
    "owner.hourJustBooked": "تم حجز هذه الساعة للتو",
    "owner.reject": "رفض",
    "owner.rejectSheet": "سبب الرفض",
    "owner.rejectConfirm": "تأكيد الرفض",
    "owner.rejectNote": "اكتب السبب",
    "owner.rejectReason.slotTaken": "الساعة محجوزة",
    "owner.rejectReason.pitchClosed": "الملعب مغلق",
    "owner.rejectReason.other": "سبب آخر",
    "owner.slotFree": "الساعة متاحة.",
    "owner.noOneWaiting": "لا أحد ينتظر هذه الساعة.",
    "owner.freeSlots": "ساعات متاحة فيها مهتمون",
    "owner.waitingSince": "ينتظر منذ",
    "owner.requestedNameDiffers": "الاسم يختلف عن المسجّل:",
    "owner.waitlist": "قائمة الانتظار",
    "owner.waitlistTab": "انتظار",
    "empty.pending": "لا طلبات معلّقة.",
    "empty.pendingNext": "عندما يطلب أحدهم ساعة، تظهر هنا.",
    "empty.waitlist": "لا قائمة انتظار.",
    "empty.waitlistNext": "من طلب ساعة محجوزة يظهر هنا بعد الإلغاء.",
  },
  en: {
    "owner.requests": "Requests",
    "owner.requestsTab": "Requests",
    "owner.pending": "Pending",
    "owner.requested": "Requested",
    "owner.newRequests": "new requests",
    "owner.approve": "Approve",
    "owner.theyPlayed": "They played",
    "owner.dismiss": "Dismiss",
    "owner.dismissAll": "Dismiss all",
    "owner.hourJustBooked": "This hour was just booked",
    "owner.reject": "Reject",
    "owner.rejectSheet": "Reject reason",
    "owner.rejectConfirm": "Confirm reject",
    "owner.rejectNote": "Write the reason",
    "owner.rejectReason.slotTaken": "Slot taken",
    "owner.rejectReason.pitchClosed": "Pitch closed",
    "owner.rejectReason.other": "Other reason",
    "owner.slotFree": "The slot is available.",
    "owner.noOneWaiting": "No one is waiting for this slot.",
    "owner.freeSlots": "Available slots with interested players",
    "owner.waitingSince": "Waiting since",
    "owner.requestedNameDiffers": "Name differs from the saved one:",
    "owner.waitlist": "Waitlist",
    "owner.waitlistTab": "Waitlist",
    "empty.pending": "No pending requests.",
    "empty.pendingNext": "When someone requests an hour, it shows here.",
    "empty.waitlist": "No waitlist.",
    "empty.waitlistNext": "Anyone who requested a taken hour shows here after a cancel.",
  },
};
