import type { CopyArea } from "./types";

/** Settings: stadium info, pitches and hours, booking rules, day start, appearance, QR. */
export const settings: CopyArea = {
  ar: {
    "theme.label": "المظهر",
    "theme.light": "فاتح",
    "theme.dark": "داكن",
    "theme.system": "نظام",
    "owner.businessMenu": "قائمة العمل",
    "owner.publicPage": "صفحتي العامة",
    "owner.stadiumInfo": "معلومات الملعب",
    "owner.stadiumName": "اسم الملعب",
    "owner.stadiumAddress": "العنوان",
    "owner.stadiumMapLink": "رابط الخريطة",
    "owner.stadiumMapHint": "رابط من خرائط Google (يبدأ بـ https)",
    "owner.stadiumPhone": "رقم الهاتف",
    "owner.stadiumWhatsappSame": "نفس الرقم للواتساب",
    "owner.stadiumWhatsapp": "رقم الواتساب",
    "owner.stadiumColour": "اللون",
    "owner.stadiumInstallHint": "اختر الاسم واللون قبل تثبيت التطبيق. الأيقونة المثبّتة لا تتغيّر بعد ذلك.",
    "owner.stadiumSave": "حفظ",
    "owner.brand.lime": "ليموني",
    "owner.brand.royal": "أزرق ملكي",
    "owner.brand.sky": "أزرق سماوي",
    "owner.brand.indigo": "نيلي",
    "owner.brand.mono": "رمادي فحمي (أحادي اللون)",
    "owner.stadiumColourNote": "الألوان تغيّر أزرار التطبيق وعناصر التمييز فقط؛ ألوان المدفوع والمستحق والحذف تبقى كما هي.",
    "owner.accentPreviewButton": "حجز",
    "owner.accentPreviewLink": "عرض",
    "owner.openPublic": "فتح",
    "owner.copyLink": "نسخ الرابط",
    "owner.copied": "تم النسخ",
    "owner.showQr": "إظهار الرمز",
    "owner.shareWhatsApp": "مشاركة عبر واتساب",
    "owner.groupBusiness": "العمل",
    "owner.groupPreferences": "التفضيلات",
    "owner.bookingRules": "قواعد الحجز",
    "owner.bookingRulesValue": "قبل الموعد",
    "owner.bookingRulesBody": "يمكن إلغاء الحجز قبل بداية الموعد ما دام المبلغ مستحقاً. لا نافذة ساعات محفوظة بعد.",
    "owner.qrTitle": "رمز الحجز",
    "owner.qrAlt": "رمز QR لصفحة الحجز",
    "owner.qrHint": "اطبعه وعلّقه على الحائط أو شاركه في مجموعات واتساب",
    "owner.qrShare": "مشاركة",
    "owner.qrDownload": "تنزيل PNG",
    "owner.qrPrint": "طباعة ملصق",
    "owner.qrScan": "امسح الرمز لحجز موعد",
    "owner.appearance": "المظهر",
    "owner.language": "اللغة",
    "owner.settings": "إعدادات",
    "owner.saveRules": "حفظ",
    "owner.splitSetting": "تقسيم الدفع بين اللاعبين",
    "owner.splitSettingHelp": "يتيح لك تقسيم دفعة المباراة بين اللاعبين.",
    "owner.rulesTrailLead": "إلغاء",
    "owner.cancelWindow": "مهلة الإلغاء (ساعات)",
    "owner.lateFee": "رسوم الإلغاء المتأخر",
    "owner.noShowFeeSetting": "رسوم عدم الحضور",
    "owner.dayStartLabel": "متى يبدأ يوم الشغل عندك؟",
    "owner.dayStartMidnight": "منتصف الليل (12:00 ص)",
    "owner.dayStartNote": "تغيير هذا يغيّر اليوم الذي تظهر تحته المباريات بعد منتصف الليل. لا يغيّر أي مبلغ.",
    "owner.dayStartWarning": "عندك ساعات مفتوحة تمتد بعد هذه الساعة: المباريات بعدها ستظهر في اليوم التالي.",
    "owner.timeDisplay": "عرض الوقت",
    "owner.timeDisplayH23": "24 ساعة (16:00)",
    "owner.timeDisplayH12": "12 ساعة (4:00 PM)",
    "owner.setTimeDisplay": "حفظ",
    "owner.pitches": "الملاعب",
    "owner.pitchNew": "ملعب جديد",
    "owner.pitchEdit": "تعديل الملعب",
    "owner.pitchName": "الاسم",
    "owner.pitchOpen": "يفتح",
    "owner.pitchClose": "يغلق",
    "owner.pitchDuration": "مدة المباراة (دقائق)",
    "owner.pitchPlayers": "عدد اللاعبين في المباراة",
    "owner.pitchPrice": "سعر المباراة",
    "owner.pitchPriceRules": "سعر مختلف في بعض الأيام",
    "owner.pitchPriceRuleAdd": "+ إضافة سعر",
    "owner.pitchGameLength": "مدة المباراة (دقائق)",
    "owner.pitchOtherLength": "غير ذلك",
    "owner.pitchMinutesFull": "دقيقة",
    "owner.pitchPriceNeeded": "اكتب سعراً لهذه الأيام.",
    "owner.pitchKeptRules": "أسعار خاصة بساعات محددة (محفوظة كما هي)",
    "owner.pitchPriceRuleConfirmDelete": "نعم، احذف",
    "owner.pitchPreview": "معاينة",
    "owner.saveChanges": "حفظ التعديلات",
    "owner.pitchLeaveConfirm": "عندك تعديلات غير محفوظة. هل تريد المغادرة بدون حفظ؟",
    "owner.pitchPriceRuleRemove": "حذف",
    "owner.pitchPriceRuleAmount": "السعر (دولار)",
    "owner.pitchHours": "ساعات الفتح",
    "owner.pitchHoursHint": "كل يوم في مجموعة واحدة. الأيام غير المختارة مغلقة.",
    "owner.pitchHoursAdd": "إضافة ساعات",
    "owner.pitchHoursRemove": "حذف",
    "owner.pitchClosed": "مغلق",
    "owner.pitchEveryDay": "كل يوم",
    "owner.dayOpen": "مفتوح",
    "owner.dayClosed": "مغلق",
    "owner.fromLabel": "من",
    "owner.toLabel": "إلى",
    "owner.pitchNextDay": "(اليوم التالي)",
    "owner.otherTime": "وقت آخر…",
    "owner.sameHoursEveryDay": "نفس الساعات كل يوم",
    "owner.pitchUntil": "حتى",
    "owner.pitchAllClosed": "مغلق كل الأيام.",
    "owner.pitchSave": "حفظ الملعب",
    "owner.pitchCreate": "إضافة الملعب",
    "owner.pitchBack": "الإعدادات",
    "owner.pitchMinutes": "دق",
    "owner.pitchConfirmPending": "نعم، احفظ واترك الطلبات المعلّقة",
    "empty.pitches": "لا ملاعب بعد.",
    "empty.pitchesNext": "تظهر الملاعب هنا عندما يُدرجها هذا الملعب.",
    "empty.noPitchEdit": "لا صلاحية لتعديل الملاعب.",
    "empty.noPitchEditNext": "هذه الصفحة للمالك.",
  },
  en: {
    "theme.label": "Theme",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "owner.businessMenu": "Business menu",
    "owner.publicPage": "My public page",
    "owner.stadiumInfo": "Stadium info",
    "owner.stadiumName": "Stadium name",
    "owner.stadiumAddress": "Address",
    "owner.stadiumMapLink": "Map link",
    "owner.stadiumMapHint": "A Google Maps link (starts with https)",
    "owner.stadiumPhone": "Phone number",
    "owner.stadiumWhatsappSame": "Same number for WhatsApp",
    "owner.stadiumWhatsapp": "WhatsApp number",
    "owner.stadiumColour": "Colour",
    "owner.stadiumInstallHint": "Set your name and colour before installing the app; the installed icon does not update afterwards.",
    "owner.stadiumSave": "Save",
    "owner.brand.lime": "Lime",
    "owner.brand.royal": "Royal blue",
    "owner.brand.sky": "Sky blue",
    "owner.brand.indigo": "Indigo",
    "owner.brand.mono": "Graphite (mono)",
    "owner.stadiumColourNote": "Colours change the app's buttons and highlights; paid, owed and delete colours stay the same.",
    "owner.accentPreviewButton": "Book",
    "owner.accentPreviewLink": "View",
    "owner.openPublic": "Open",
    "owner.copyLink": "Copy link",
    "owner.copied": "Copied",
    "owner.showQr": "Show QR",
    "owner.shareWhatsApp": "Share on WhatsApp",
    "owner.groupBusiness": "Business",
    "owner.groupPreferences": "Preferences",
    "owner.bookingRules": "Booking rules",
    "owner.bookingRulesValue": "Before the slot",
    "owner.bookingRulesBody": "A booking can be cancelled before it starts while money is still due. No hours window is stored yet.",
    "owner.qrTitle": "Booking QR",
    "owner.qrAlt": "QR code for the booking page",
    "owner.qrHint": "Print it for your wall or share it in WhatsApp groups",
    "owner.qrShare": "Share",
    "owner.qrDownload": "Download PNG",
    "owner.qrPrint": "Print poster",
    "owner.qrScan": "Scan to book",
    "owner.appearance": "Appearance",
    "owner.language": "Language",
    "owner.settings": "Settings",
    "owner.saveRules": "Save",
    "owner.splitSetting": "Per-player split",
    "owner.splitSettingHelp": "Lets you split a game's payment between players.",
    "owner.rulesTrailLead": "Cancel",
    "owner.cancelWindow": "Cancellation window (hours)",
    "owner.lateFee": "Late cancellation fee",
    "owner.noShowFeeSetting": "No-show fee",
    "owner.dayStartLabel": "When does your business day start?",
    "owner.dayStartMidnight": "Midnight (12:00 AM)",
    "owner.dayStartNote": "Changing this changes which day games after midnight appear under. It changes no amounts.",
    "owner.dayStartWarning": "Some pitch hours run past this hour: games after it will show on the next day.",
    "owner.timeDisplay": "Time format",
    "owner.timeDisplayH23": "24-hour (16:00)",
    "owner.timeDisplayH12": "12-hour (4:00 PM)",
    "owner.setTimeDisplay": "Save",
    "owner.pitches": "Pitches",
    "owner.pitchNew": "New pitch",
    "owner.pitchEdit": "Edit pitch",
    "owner.pitchName": "Name",
    "owner.pitchOpen": "Opens",
    "owner.pitchClose": "Closes",
    "owner.pitchDuration": "Game length (minutes)",
    "owner.pitchPlayers": "Players per game",
    "owner.pitchPrice": "Price per game",
    "owner.pitchPriceRules": "Different price on some days",
    "owner.pitchPriceRuleAdd": "+ Add a price",
    "owner.pitchGameLength": "Game length (minutes)",
    "owner.pitchOtherLength": "Other",
    "owner.pitchMinutesFull": "minutes",
    "owner.pitchPriceNeeded": "Enter a price for these days.",
    "owner.pitchKeptRules": "Special prices for set hours (kept as they are)",
    "owner.pitchPriceRuleConfirmDelete": "Yes, delete",
    "owner.pitchPreview": "Preview",
    "owner.saveChanges": "Save changes",
    "owner.pitchLeaveConfirm": "You have unsaved changes. Leave without saving?",
    "owner.pitchPriceRuleRemove": "Remove",
    "owner.pitchPriceRuleAmount": "Price (USD)",
    "owner.pitchHours": "Opening hours",
    "owner.pitchHoursHint": "Each day belongs to one group. Unchecked days are closed.",
    "owner.pitchHoursAdd": "Add hours",
    "owner.pitchHoursRemove": "Remove",
    "owner.pitchClosed": "closed",
    "owner.pitchEveryDay": "Every day",
    "owner.dayOpen": "Open",
    "owner.dayClosed": "Closed",
    "owner.fromLabel": "From",
    "owner.toLabel": "To",
    "owner.pitchNextDay": "(next day)",
    "owner.otherTime": "Other time…",
    "owner.sameHoursEveryDay": "Same hours every day",
    "owner.pitchUntil": "until",
    "owner.pitchAllClosed": "Closed every day.",
    "owner.pitchSave": "Save pitch",
    "owner.pitchCreate": "Add pitch",
    "owner.pitchBack": "Settings",
    "owner.pitchMinutes": "min",
    "owner.pitchConfirmPending": "Yes, save and leave pending requests as they are",
    "empty.pitches": "No pitches yet.",
    "empty.pitchesNext": "Pitches show here when this stadium lists them.",
    "empty.noPitchEdit": "No permission to edit pitches.",
    "empty.noPitchEditNext": "This page is for the owner.",
  },
};
