import type { CopyArea } from "./types";

/** Shop: items, sales, items on a game. */
export const shop: CopyArea = {
  ar: {
    "owner.shopAddShort": "+ إضافة",
    "owner.shopNoSales": "لا مبيعات في هذه الفترة.",
    "owner.shopSales": "المبيعات",
    "owner.shopSupplies": "المستلزمات",
    "owner.shopCaption": "المبيعات تشمل أصنافاً على مباريات غير مدفوعة بعد.",
    "owner.shopItems": "الأصناف المباعة",
    "owner.shopSoldLine": "الأصناف",
    "owner.shop": "المتجر",
    "owner.shopAdd": "إضافة صنف",
    "owner.shopEdit": "تعديل الصنف",
    "owner.shopEmpty": "لا أصناف بعد. أضف أول صنف.",
    "owner.shopName": "الاسم",
    "owner.shopPrice": "السعر (دولار)",
    "owner.shopPriceNote": "تغيير السعر يؤثر على المبيعات القادمة فقط.",
    "owner.shopSave": "حفظ",
    "owner.shopArchive": "أرشفة الصنف",
    "owner.shopArchiveAsk": "لن يظهر للبيع، وتبقى المبيعات السابقة كما هي.",
    "owner.shopArchiveConfirm": "نعم، أرشف",
    "owner.shopNoAccess": "المتجر للمالك فقط.",
    "owner.shopNoAccessNext": "اطلب من المالك.",
    "owner.sell": "بيع",
    "owner.sellTotal": "المجموع",
    "owner.sellMinus": "إنقاص",
    "owner.rateFirst": "حدّد سعر الصرف أولاً لبيع أصناف بالليرة.",
    "owner.rateFirstLink": "سعر الصرف",
    "owner.paidInFull": "مدفوع بالكامل",
    "owner.changeLabel": "الباقي للزبون",
    "owner.shopCurrency": "العملة",
    "owner.addItems": "إضافة أصناف",
    "owner.itemsOnGame": "على المباراة (الحاجز)",
    "owner.itemsChargeTo": "على حساب مَن؟",
    "owner.itemsSomeoneElse": "+ شخص آخر",
    "owner.itemsNameOrPhone": "الاسم أو الهاتف",
    "owner.itemsPhoneField": "الهاتف",
    "owner.itemsPlusPhone": "+ هاتف",
    "owner.addWord": "إضافة",
    "owner.sellNoItems": "لا أصناف للبيع بعد.",
    "owner.sellFirstItem": "أضف أول صنف",
    "owner.sellFirstItemStaff": "اطلب من المالك إضافة أصناف.",
    "owner.sellNoAccess": "لا صلاحية للبيع.",
    "owner.sellNoAccessNext": "اطلب من المالك أن يمنحك صلاحية البيع.",
  },
  en: {
    "owner.shopAddShort": "+ Add",
    "owner.shopNoSales": "No sales in this period.",
    "owner.shopSales": "Sales",
    "owner.shopSupplies": "Supplies",
    "owner.shopCaption": "Sales include items on games that are not paid yet.",
    "owner.shopItems": "Items sold",
    "owner.shopSoldLine": "Items",
    "owner.shop": "Shop",
    "owner.shopAdd": "Add item",
    "owner.shopEdit": "Edit item",
    "owner.shopEmpty": "No items yet. Add your first item.",
    "owner.shopName": "Name",
    "owner.shopPrice": "Price (USD)",
    "owner.shopPriceNote": "A new price applies to future sales only.",
    "owner.shopSave": "Save",
    "owner.shopArchive": "Archive item",
    "owner.shopArchiveAsk": "It stops showing for sale. Past sales keep it.",
    "owner.shopArchiveConfirm": "Yes, archive",
    "owner.shopNoAccess": "The shop catalog is for the owner.",
    "owner.shopNoAccessNext": "Ask the owner.",
    "owner.sell": "Sell",
    "owner.sellTotal": "Total",
    "owner.sellMinus": "Remove one",
    "owner.rateFirst": "Set the exchange rate first to sell items priced in LBP.",
    "owner.rateFirstLink": "Exchange rate",
    "owner.paidInFull": "Paid in full",
    "owner.changeLabel": "Change",
    "owner.shopCurrency": "Currency",
    "owner.addItems": "Add items",
    "owner.itemsOnGame": "On the game (booker)",
    "owner.itemsChargeTo": "Charge to",
    "owner.itemsSomeoneElse": "+ Someone else",
    "owner.itemsNameOrPhone": "Name or phone",
    "owner.itemsPhoneField": "Phone",
    "owner.itemsPlusPhone": "+ phone",
    "owner.addWord": "Add",
    "owner.sellNoItems": "No items to sell yet.",
    "owner.sellFirstItem": "Add your first item",
    "owner.sellFirstItemStaff": "Ask the owner to add items.",
    "owner.sellNoAccess": "You cannot sell.",
    "owner.sellNoAccessNext": "Ask the owner to give you the sell permission.",
  },
};
