import type { CopyArea } from "./types";

/** Today and booking: games, day view, series, extensions, cancel and no-show, empty states. */
export const today: CopyArea = {
  ar: {
    "owner.seriesSheetTitle": "الحجز الثابت",
    "owner.seriesRowLine": "↻ أسبوعي · كل {weekday} {time} · بقي {left} · حتى {until}",
    "owner.seriesRowEnded": "↻ أسبوعي · كل {weekday} {time} · انتهى",
    "owner.seriesCardMark": "حجز أسبوعي",
    "owner.seriesWeek.upcoming": "قادمة",
    "owner.seriesWeek.played": "لُعبت",
    "owner.seriesWeek.cancelled": "ملغاة",
    "owner.seriesWeek.no_show": "لم يحضر",
    "owner.seriesRenew": "تجديد 8 أسابيع أخرى",
    "owner.seriesCancelRest": "إلغاء الباقي",
    "owner.seriesCancelAsk": "ستُلغى {games} بلا رسوم.",
    "owner.seriesLeftAlone": "هذه الأسابيع عليها مدفوعات وتبقى. ألغِها واحدة واحدة:",
    "owner.seriesCancelConfirm": "نعم، ألغِ الباقي",
    "owner.seriesCancelDone": "أُلغيت {games}.",
    "owner.weeklyBookings": "الحجوزات الثابتة",
    "owner.weeklyEvery": "كل {weekday} {time}",
    "owner.weeklyPerson": "أسبوعياً كل {weekday} {time}",
    "owner.weeklyLeft": "بقي {n}",
    "owner.weeklyRenew": "تجديد",
    "owner.weeklyEmpty": "لا حجوزات ثابتة.",
    "owner.weeklyEmptyNext": "الحجز الثابت يظهر هنا.",
    "owner.weeklyEndingOne": "حجز ثابت ينتهي قريباً: {name}، {weekday} {time}",
    "owner.weeklyEndingMany": "{n} حجوزات ثابتة تنتهي قريباً",
    "owner.repeatWeekly": "كرّر كل أسبوع",
    "owner.seriesWeeks": "عدد الأسابيع",
    "owner.seriesTaken": "محجوز",
    "owner.seriesOutside": "خارج ساعات العمل",
    "owner.seriesPast": "مضى",
    "owner.seriesDeclines": "سيُرفض {n} من الطلبات",
    "owner.seriesNone": "لا يوجد أسبوع متاح.",
    "owner.seriesChecking": "نتحقق من الأسابيع…",
    "owner.seriesCreatedTitle": "تم الحجز الثابت",
    "owner.seriesCreatedLine": "كل {weekday} الساعة {time}، ابتداءً من {day}",
    "owner.seriesSkippedLead": "تخطّينا (صار محجوزاً بعد المعاينة):",
    "owner.seriesDone": "تم",
    "owner.extendedChip": "+{n} د",
    "owner.extendedTitle": "مُدّدت المباراة {n} دقيقة",
    "owner.extend": "تمديد 30 دقيقة",
    "owner.extendNewTime": "الوقت الجديد",
    "owner.extendAdded": "السعر المضاف",
    "owner.extendDeclines": "سيُرفض {n} من الطلبات.",
    "owner.extendConfirm": "تأكيد",
    "owner.extendDone": "تم تمديد المباراة.",
    "owner.extendNextGame": "المباراة التالية الساعة {time}",
    "owner.extendClosing": "يغلق الملعب الساعة {time}",
    "owner.extendMax": "الحد الأقصى ٣ ساعات",
    "empty.games": "لا مباريات في هذا اليوم.",
    "empty.gamesNext": "الحجوزات المؤكدة لهذا اليوم تظهر هنا.",
    "owner.recordBooking": "حجز",
    "owner.personGames": "المباريات",
    "owner.noPersonGames": "لا مباريات بعد",
    "owner.noPersonGamesNext": "مبارياته تظهر هنا",
    "owner.confirmed": "مؤكد",
    "owner.live": "مباشر",
    "owner.minLeft": "د متبقية",
    "owner.callPlayer": "اتصال باللاعب",
    "owner.hideCollectMixed": "إخفاء الدفع بعملتين",
    "owner.cancelHint": "ستُلغى الساعة وتصبح متاحة مجدداً.",
    "owner.playerCancelled": "اللاعب ألغى",
    "owner.ownerCancelled": "أنا ألغيت",
    "owner.cancelConfirm": "تأكيد إلغاء الحجز",
    "owner.cancelBack": "تراجع",
    "owner.noShow": "لم يحضر",
    "owner.freeStrip": "أوقات متاحة",
    "owner.closedCell": "مغلق",
    "owner.availableHours": "ساعات متاحة",
    "owner.gamesHeading": "المباريات",
    "owner.earlierDebtsHeading": "للتحصيل من أيام سابقة",
    "owner.moreSlots": "أخرى",
    "owner.allPitches": "الكل",
    "owner.afterMidnightToday": "بعد منتصف الليل: اليوم مستمر حتى {time}.",
    "owner.monthCalendar": "الشهر",
    "owner.cancelledShort": "ملغى",
    "owner.bookHeading": "احجز ساعة",
    "owner.showSlots": "عرض الساعات",
    "owner.book": "احجز",
    "owner.openBooking": "عرض التفاصيل",
    "empty.confirmed": "لا مباريات مؤكدة اليوم.",
    "empty.confirmedNext": "الساعات الموافق عليها تظهر هنا.",
    "empty.noCreate": "لا صلاحية للحجز.",
    "empty.noCreateNext": "هذه الصفحة للمالك أو لمن أُعطي صلاحية الحجز.",
  },
  en: {
    "owner.seriesSheetTitle": "Weekly booking",
    "owner.seriesRowLine": "↻ Weekly · every {weekday} {time} · {left} left · until {until}",
    "owner.seriesRowEnded": "↻ Weekly · every {weekday} {time} · ended",
    "owner.seriesCardMark": "Weekly booking",
    "owner.seriesWeek.upcoming": "Upcoming",
    "owner.seriesWeek.played": "Played",
    "owner.seriesWeek.cancelled": "Cancelled",
    "owner.seriesWeek.no_show": "No-show",
    "owner.seriesRenew": "Renew 8 more weeks",
    "owner.seriesCancelRest": "Cancel the rest",
    "owner.seriesCancelAsk": "{games} will be cancelled with no fee.",
    "owner.seriesLeftAlone": "These weeks have payments and stay. Cancel them one by one:",
    "owner.seriesCancelConfirm": "Yes, cancel the rest",
    "owner.seriesCancelDone": "{games} cancelled.",
    "owner.weeklyBookings": "Weekly bookings",
    "owner.weeklyEvery": "Every {weekday} {time}",
    "owner.weeklyPerson": "Weekly every {weekday} {time}",
    "owner.weeklyLeft": "{n} left",
    "owner.weeklyRenew": "Renew",
    "owner.weeklyEmpty": "No weekly bookings.",
    "owner.weeklyEmptyNext": "A weekly booking shows here.",
    "owner.weeklyEndingOne": "Weekly booking ending soon: {name}, {weekday} {time}",
    "owner.weeklyEndingMany": "{n} weekly bookings ending soon",
    "owner.repeatWeekly": "Repeat weekly",
    "owner.seriesWeeks": "Number of weeks",
    "owner.seriesTaken": "Taken",
    "owner.seriesOutside": "Outside hours",
    "owner.seriesPast": "Past",
    "owner.seriesDeclines": "{n} requests will be declined",
    "owner.seriesNone": "No week is free.",
    "owner.seriesChecking": "Checking the weeks…",
    "owner.seriesCreatedTitle": "Weekly booking made",
    "owner.seriesCreatedLine": "Every {weekday} at {time}, starting {day}",
    "owner.seriesSkippedLead": "Skipped (taken since the preview):",
    "owner.seriesDone": "Done",
    "owner.extendedChip": "+{n} min",
    "owner.extendedTitle": "Extended by {n} min",
    "owner.extend": "Extend 30 min",
    "owner.extendNewTime": "New time",
    "owner.extendAdded": "Added price",
    "owner.extendDeclines": "{n} requests will be declined.",
    "owner.extendConfirm": "Confirm",
    "owner.extendDone": "Game extended.",
    "owner.extendNextGame": "Next game at {time}",
    "owner.extendClosing": "Closes at {time}",
    "owner.extendMax": "Max 3 hours",
    "empty.games": "No games on this day.",
    "empty.gamesNext": "Confirmed bookings for this day show here.",
    "owner.recordBooking": "Booking",
    "owner.personGames": "Games",
    "owner.noPersonGames": "No games yet",
    "owner.noPersonGamesNext": "Their games show here",
    "owner.confirmed": "Confirmed",
    "owner.live": "Live",
    "owner.minLeft": "min left",
    "owner.callPlayer": "Call player",
    "owner.hideCollectMixed": "Hide two-currency pay",
    "owner.cancelHint": "This hour will be freed and offered again.",
    "owner.playerCancelled": "Player cancelled",
    "owner.ownerCancelled": "I cancelled",
    "owner.cancelConfirm": "Confirm cancel booking",
    "owner.cancelBack": "Never mind",
    "owner.noShow": "No-show",
    "owner.freeStrip": "Free slots",
    "owner.closedCell": "Closed",
    "owner.availableHours": "Available hours",
    "owner.gamesHeading": "Games",
    "owner.earlierDebtsHeading": "To collect from earlier days",
    "owner.moreSlots": "more",
    "owner.allPitches": "All",
    "owner.afterMidnightToday": "After midnight: Today runs until {time}.",
    "owner.monthCalendar": "Month",
    "owner.cancelledShort": "Cancelled",
    "owner.bookHeading": "Book an hour",
    "owner.showSlots": "Show hours",
    "owner.book": "Book",
    "owner.openBooking": "View details",
    "empty.confirmed": "No confirmed matches today.",
    "empty.confirmedNext": "Approved hours show here.",
    "empty.noCreate": "No permission to book.",
    "empty.noCreateNext": "This page is for the owner or anyone given booking access.",
  },
};
